// Backward-compatibility: legacy English-name IDs -> stable slugs.
// Generated. Keep so old URLs (?from/?to), APIs and schedule-data keep resolving.
import type { StationId } from "./types";

export const STATION_ALIASES: Record<string, StationId> = {
  "Tajrish": "tajrish",
  "Gheytariyeh": "gheytariyeh",
  "Shahid Sadr": "shahid-sadr",
  "Qolhak": "qolhak",
  "Doctor Shariati": "doctor-shariati",
  "Mirdamad": "mirdamad",
  "Shahid Haghani": "shahid-haghani",
  "Shahid Hemmat": "shahid-hemmat",
  "Mosalla-ye Imam Khomeini": "mosalla-ye-imam-khomeini",
  "Shahid Beheshti": "shahid-beheshti",
  "Shahid Mofattah": "shahid-mofattah",
  "Ayatollah Taleghani": "ayatollah-taleghani",
  "Darvazeh Dolat": "darvazeh-dolat",
  "Sa'adi": "saadi",
  "Imam Khomeini": "imam-khomeini",
  "Panzdah-e Khordad": "panzdah-e-khordad",
  "Khayyam": "khayyam",
  "Meydan-e Mohammadiyeh": "meydan-e-mohammadiyeh",
  "Shoush": "shoush",
  "Payaneh Jonoub(Jonoub Terminal)": "payaneh-jonoub-jonoub-terminal",
  "Shahid Bokharaei": "shahid-bokharaei",
  "Aliabad": "aliabad",
  "Javanmard-e Ghassab": "javanmard-e-ghassab",
  "Shahr-e Rey": "shahr-e-rey",
  "Palayeshgah": "palayeshgah",
  "Shahed - BagherShahr": "shahed-baghershahr",
  "Namayeshgah-e Shahr-e Aftab": "namayeshgah-e-shahr-e-aftab",
  "Vavan": "vavan",
  "Emam Khomeini Airport": "emam-khomeini-airport",
  "Shahr-e Parand": "shahr-e-parand",
  "Holy Shrine of Imam Khomeini": "holy-shrine-of-imam-khomeini",
  "Kahrizak": "kahrizak",
  "Farhangsara": "farhangsara",
  "Tehranpars": "tehranpars",
  "Shahid Bagheri": "shahid-bagheri",
  "Daneshgah-e Elm-o San'at": "daneshgah-e-elm-o-sanat",
  "Sarsabz": "sarsabz",
  "Janbazan": "janbazan",
  "Fadak": "fadak",
  "Sabalan": "sabalan",
  "Shahid Madani": "shahid-madani",
  "Imam Hossein": "imam-hossein",
  "Darvazeh Shemiran": "darvazeh-shemiran",
  "Baharistan": "baharistan",
  "Mellat": "mellat",
  "Hasan Abad": "hasan-abad",
  "Daneshgah-e Imam Ali": "daneshgah-e-imam-ali",
  "Meydan-e Horr": "meydan-e-horr",
  "Shahid Navab-e Safavi": "shahid-navab-e-safavi",
  "Shademan": "shademan",
  "Daneshgah-e Sharif": "daneshgah-e-sharif",
  "Tarasht": "tarasht",
  "Tehran (Sadeghiyeh)": "tehran-sadeghiyeh",
  "Qa'em": "qaem",
  "Shahid Mahallati": "shahid-mahallati",
  "Aghdasiyeh": "aghdasiyeh",
  "Nobonyad": "nobonyad",
  "Hossein Abad": "hossein-abad",
  "Meydan-e Heravi": "meydan-e-heravi",
  "Shahid Zeynoddin": "shahid-zeynoddin",
  "Khajeh Abdollah-e Ansari": "khajeh-abdollah-e-ansari",
  "Shahid Sayyad Shirazi": "shahid-sayyad-shirazi",
  "Shahid Ghodousi": "shahid-ghodousi",
  "Sohrevardi": "sohrevardi",
  "Mirza-ye Shirazi": "mirza-ye-shirazi",
  "Meydan-e Jahad": "meydan-e-jahad",
  "Teatr-e Shahr": "teatr-e-shahr",
  "Moniriyeh": "moniriyeh",
  "Mahdiyeh": "mahdiyeh",
  "Rahahan": "rahahan",
  "Javadiyeh": "javadiyeh",
  "Zamzam": "zamzam",
  "Shahrak-e Shariaty": "shahrak-e-shariaty",
  "Abdol Abad": "abdol-abad",
  "Nemat Abad": "nemat-abad",
  "Azadegan": "azadegan",
  "Shahid Kolahdooz": "shahid-kolahdooz",
  "Nirou Havaei": "nirou-havaei",
  "Nabard": "nabard",
  "Piroozi": "piroozi",
  "Ebn-e Sina": "ebn-e-sina",
  "Ferdowsi": "ferdowsi",
  "Meydan-e Enghelab-e Eslami": "meydan-e-enghelab-e-eslami",
  "Towhid": "towhid",
  "Doctor Habibollah": "doctor-habibollah",
  "Ostad Mo'in": "ostad-moin",
  "Meydan-e Azadi": "meydan-e-azadi",
  "Bimeh": "bimeh",
  "Mehrabad Airport Terminal 1&2": "mehrabad-airport-terminal-1-2",
  "Mehrabad Airport Terminal 4&6": "mehrabad-airport-terminal-4-6",
  "Shahrak-e Ekbatan": "shahrak-e-ekbatan",
  "Allameh Jafari": "allameh-jafari",
  "Chaharbagh": "chaharbagh",
  "Eram-e Sabz": "eram-e-sabz",
  "Varzeshgah-e Azadi": "varzeshgah-e-azadi",
  "Chitgar": "chitgar",
  "Iran Khodro": "iran-khodro",
  "Vardavard": "vardavard",
  "Garmdareh": "garmdareh",
  "Atmosphere": "atmosphere",
  "Karaj": "karaj",
  "Mohammadshahr": "mohammadshahr",
  "Golshahr": "golshahr",
  "Shahid Sepahbod Qasem Soleimani": "shahid-sepahbod-qasem-soleimani",
  "Haram-e Hazrat-e Abdol Azim": "haram-e-hazrat-e-abdol-azim",
  "Meydan-e Hazrat-e Abdol Azim": "meydan-e-hazrat-e-abdol-azim",
  "Ebn-e Babviyeh": "ebn-e-babviyeh",
  "Cheshmeh Ali": "cheshmeh-ali",
  "Shohada-ye Dowlat Abad": "shohada-ye-dowlat-abad",
  "Kiyan Shahr": "kiyan-shahr",
  "Be'sat": "besat",
  "Shahid Rezaei": "shahid-rezaei",
  "Meydan-e Khorasan": "meydan-e-khorasan",
  "Shohada-ye Hefdah-e Shahrivar": "shohada-ye-hefdah-e-shahrivar",
  "Amirkabir": "amirkabir",
  "Meydan-e Shohada": "meydan-e-shohada",
  "Sarbaz": "sarbaz",
  "Bahar Shiraz (Khanevadeh Hospital)": "bahar-shiraz-khanevadeh-hospital",
  "Shohada-ye Haftom-e Tir": "shohada-ye-haftom-e-tir",
  "Maryam-e Moghaddas": "maryam-e-moghaddas",
  "Meydan-e Hazrat Vali Asr": "meydan-e-hazrat-vali-asr",
  "Bustan-e Laleh": "bustan-e-laleh",
  "Karagar": "karagar",
  "Daneshgah-e Tarbiat Modarres": "daneshgah-e-tarbiat-modarres",
  "Shahrak-e Azmayesh": "shahrak-e-azmayesh",
  "Marzdaran": "marzdaran",
  "Yadegar-e Imam": "yadegar-e-imam",
  "Shahid Ashrafi Esfahani": "shahid-ashrafi-esfahani",
  "Shahid Sattari": "shahid-sattari",
  "Ayatollah Kashani": "ayatollah-kashani",
  "Shahr-e Ziba": "shahr-e-ziba",
  "Shahran": "shahran",
  "Shohada-ye Kan": "shohada-ye-kan",
  "Kouhsar": "kouhsar",
  "Varzeshgah-e Takhti": "varzeshgah-e-takhti",
  "Basij": "basij",
  "Ahang": "ahang",
  "Chehel Tan-e Doulab": "chehel-tan-e-doulab",
  "Meydan-e Giyam": "meydan-e-giyam",
  "Mowlavi": "mowlavi",
  "Helal Ahmar": "helal-ahmar",
  "Beryanak": "beryanak",
  "Komeyl": "komeyl",
  "Roudaki": "roudaki",
  "Modafean-e Salamat": "modafean-e-salamat",
  "Boostan-e Goftegou": "boostan-e-goftegou",
  "Milad Tower": "milad-tower",
  "Meydan-e San'at": "meydan-e-sanat",
  "Shahid Dadman": "shahid-dadman",
  "Meydan-e Ketab": "meydan-e-ketab",
  // Shahid Fakhrizadeh: historical / alternate names (station record added
  // separately; canonical ID stays shahid-fakhrizadeh).
  "Shahid Fakhrizade": "shahid-fakhrizadeh",
  "Shahid Fakhrizadeh Metro Station": "shahid-fakhrizadeh",
  "Mammut": "shahid-fakhrizadeh",
  "Mammut Metro Station": "shahid-fakhrizadeh",
  "ماموت": "shahid-fakhrizadeh",
  "ایستگاه مترو شهید فخری زاده": "shahid-fakhrizadeh",
  // Historical name from older map extractions.
  "Shahid Nejatollahi": "maryam-e-moghaddas",
  // Source transliteration variants. Canonical IDs never change for these.
  "Gholhak": "qolhak",
  "Darvazeh Dowlat": "darvazeh-dolat",
  "Pirouzi": "piroozi",
  "Garmdarreh": "garmdareh",
  "Atmosfer": "atmosphere",
};
