// SPDX-License-Identifier: ODbL-1.0 — part of Metto's ODbL-1.0 adapted metro database. See DATA_LICENSE.md.
import type { MetroRoute } from "./types";

// Ordered routes. Junction stations appear in every route they serve — as ONE
// shared station record, never duplicated.
//
// Corrections applied vs legacy relations:
// - Line 1 north: shahid-sadr -> qolhak (legacy had a "Shahid Sadr" self-loop
//   and Qolhak -> Shahid Sadr without the return edge).
// - Line 4 west is one continuous route:
//   ... eram-e-sabz -> allameh-jafari -> ayatollah-kashani -> chaharbagh.
//   Eram <-> Allameh is operational; the western extension (Allameh <->
//   Kashani, Kashani <-> Chaharbagh) is under construction. Kashani's Line 4
//   stop is therefore under_construction while the physical station (Line 6)
//   is operational.
// - Branches are explicit routes sharing the junction station:
//   Line 1 Parand branch (shahed-bagher-shahr), Line 4 Mehrabad branch (bimeh).
// - Line 5 west: ... golshahr -> shahid-fakhrizadeh ->
//   shahid-sepahbod-qasem-soleimani (Fakhrizadeh record added; coords/address
//   per supplied data, amenities unverified — see NOTES.md).

export const ROUTES: MetroRoute[] = [
  {
    id: "line-1-main",
    lineId: 1,
    stops: [
      { stationId: "tajrish", status: "operational" },
      { stationId: "gheytariyeh", status: "operational" },
      { stationId: "shahid-sadr", status: "operational" },
      { stationId: "qolhak", status: "operational" },
      { stationId: "doctor-shariati", status: "operational" },
      { stationId: "mirdamad", status: "operational" },
      { stationId: "shahid-haghani", status: "operational" },
      { stationId: "shahid-hemmat", status: "operational" },
      { stationId: "mosalla-ye-imam-khomeini", status: "operational" },
      { stationId: "shahid-beheshti", status: "operational" },
      { stationId: "shahid-mofattah", status: "operational" },
      { stationId: "shohada-ye-haftom-e-tir", status: "operational" },
      { stationId: "ayatollah-taleghani", status: "operational" },
      { stationId: "darvazeh-dolat", status: "operational" },
      { stationId: "saadi", status: "operational" },
      { stationId: "imam-khomeini", status: "operational" },
      { stationId: "panzdah-e-khordad", status: "operational" },
      { stationId: "khayyam", status: "operational" },
      { stationId: "meydan-e-mohammadiyeh", status: "operational" },
      { stationId: "shoush", status: "operational" },
      { stationId: "payaneh-jonoub-jonoub-terminal", status: "operational" },
      { stationId: "shahid-bokharaei", status: "operational" },
      { stationId: "aliabad", status: "operational" },
      { stationId: "javanmard-e-ghassab", status: "operational" },
      { stationId: "shahr-e-rey", status: "operational" },
      { stationId: "palayeshgah", status: "operational" },
      { stationId: "shahed-baghershahr", status: "operational" },
      { stationId: "holy-shrine-of-imam-khomeini", status: "operational" },
      { stationId: "kahrizak", status: "operational" },
    ],
  },
  {
    id: "line-1-parand",
    lineId: 1,
    branchId: "parand",
    stops: [
      { stationId: "shahed-baghershahr", status: "operational" },
      { stationId: "namayeshgah-e-shahr-e-aftab", status: "operational" },
      { stationId: "vavan", status: "operational" },
      { stationId: "emam-khomeini-airport", status: "operational" },
      { stationId: "shahr-e-parand", status: "operational" },
    ],
  },
  {
    id: "line-2-main",
    lineId: 2,
    stops: [
      { stationId: "farhangsara", status: "operational" },
      { stationId: "tehranpars", status: "operational" },
      { stationId: "shahid-bagheri", status: "operational" },
      { stationId: "daneshgah-e-elm-o-sanat", status: "operational" },
      { stationId: "sarsabz", status: "operational" },
      { stationId: "janbazan", status: "operational" },
      { stationId: "fadak", status: "operational" },
      { stationId: "sabalan", status: "operational" },
      { stationId: "shahid-madani", status: "operational" },
      { stationId: "imam-hossein", status: "operational" },
      { stationId: "darvazeh-shemiran", status: "operational" },
      { stationId: "baharistan", status: "operational" },
      { stationId: "mellat", status: "operational" },
      { stationId: "imam-khomeini", status: "operational" },
      { stationId: "hasan-abad", status: "operational" },
      { stationId: "daneshgah-e-imam-ali", status: "operational" },
      { stationId: "meydan-e-horr", status: "operational" },
      { stationId: "shahid-navab-e-safavi", status: "operational" },
      { stationId: "shademan", status: "operational" },
      { stationId: "daneshgah-e-sharif", status: "operational" },
      { stationId: "tarasht", status: "operational" },
      { stationId: "tehran-sadeghiyeh", status: "operational" },
    ],
  },
  {
    id: "line-3-main",
    lineId: 3,
    stops: [
      { stationId: "qaem", status: "operational" },
      { stationId: "shahid-mahallati", status: "operational" },
      { stationId: "aghdasiyeh", status: "operational" },
      { stationId: "nobonyad", status: "operational" },
      { stationId: "hossein-abad", status: "operational" },
      { stationId: "meydan-e-heravi", status: "operational" },
      { stationId: "shahid-zeynoddin", status: "operational" },
      { stationId: "khajeh-abdollah-e-ansari", status: "operational" },
      { stationId: "shahid-sayyad-shirazi", status: "operational" },
      { stationId: "shahid-ghodousi", status: "operational" },
      { stationId: "sohrevardi", status: "operational" },
      { stationId: "shahid-beheshti", status: "operational" },
      { stationId: "mirza-ye-shirazi", status: "operational" },
      { stationId: "meydan-e-jahad", status: "operational" },
      { stationId: "meydan-e-hazrat-vali-asr", status: "operational" },
      { stationId: "teatr-e-shahr", status: "operational" },
      { stationId: "moniriyeh", status: "operational" },
      { stationId: "mahdiyeh", status: "operational" },
      { stationId: "rahahan", status: "operational" },
      { stationId: "javadiyeh", status: "operational" },
      { stationId: "zamzam", status: "operational" },
      { stationId: "shahrak-e-shariaty", status: "operational" },
      { stationId: "abdol-abad", status: "operational" },
      { stationId: "nemat-abad", status: "operational" },
      { stationId: "azadegan", status: "operational" },
    ],
  },
  {
    id: "line-4-main",
    lineId: 4,
    stops: [
      { stationId: "shahid-kolahdooz", status: "operational" },
      { stationId: "nirou-havaei", status: "operational" },
      { stationId: "nabard", status: "operational" },
      { stationId: "piroozi", status: "operational" },
      { stationId: "ebn-e-sina", status: "operational" },
      { stationId: "meydan-e-shohada", status: "operational" },
      { stationId: "darvazeh-shemiran", status: "operational" },
      { stationId: "darvazeh-dolat", status: "operational" },
      { stationId: "ferdowsi", status: "operational" },
      { stationId: "teatr-e-shahr", status: "operational" },
      { stationId: "meydan-e-enghelab-e-eslami", status: "operational" },
      { stationId: "towhid", status: "operational" },
      { stationId: "shademan", status: "operational" },
      { stationId: "doctor-habibollah", status: "operational" },
      { stationId: "ostad-moin", status: "operational" },
      { stationId: "meydan-e-azadi", status: "operational" },
      { stationId: "bimeh", status: "operational" },
      { stationId: "shahrak-e-ekbatan", status: "operational" },
      { stationId: "eram-e-sabz", status: "operational" },
      { stationId: "allameh-jafari", status: "operational" },
      { stationId: "ayatollah-kashani", status: "under_construction" },
      { stationId: "chaharbagh", status: "under_construction" },
    ],
  },
  {
    id: "line-4-mehrabad",
    lineId: 4,
    branchId: "mehrabad",
    stops: [
      { stationId: "bimeh", status: "operational" },
      { stationId: "mehrabad-airport-terminal-1-2", status: "operational" },
      { stationId: "mehrabad-airport-terminal-4-6", status: "operational" },
    ],
  },
  {
    id: "line-5-main",
    lineId: 5,
    stops: [
      { stationId: "tehran-sadeghiyeh", status: "operational" },
      { stationId: "eram-e-sabz", status: "operational" },
      { stationId: "varzeshgah-e-azadi", status: "operational" },
      { stationId: "chitgar", status: "operational" },
      { stationId: "iran-khodro", status: "operational" },
      { stationId: "vardavard", status: "operational" },
      { stationId: "garmdareh", status: "operational" },
      { stationId: "atmosphere", status: "operational" },
      { stationId: "karaj", status: "operational" },
      { stationId: "mohammadshahr", status: "operational" },
      { stationId: "golshahr", status: "operational" },
      { stationId: "shahid-fakhrizadeh", status: "operational" },
      { stationId: "shahid-sepahbod-qasem-soleimani", status: "operational" },
    ],
  },
  {
    id: "line-6-main",
    lineId: 6,
    stops: [
      { stationId: "kouhsar", status: "operational" },
      { stationId: "shohada-ye-kan", status: "operational" },
      { stationId: "shahran", status: "operational" },
      { stationId: "shahr-e-ziba", status: "operational" },
      { stationId: "ayatollah-kashani", status: "operational" },
      { stationId: "shahid-sattari", status: "operational" },
      { stationId: "shahid-ashrafi-esfahani", status: "operational" },
      { stationId: "yadegar-e-imam", status: "operational" },
      { stationId: "marzdaran", status: "operational" },
      { stationId: "shahrak-e-azmayesh", status: "operational" },
      { stationId: "daneshgah-e-tarbiat-modarres", status: "operational" },
      { stationId: "karagar", status: "operational" },
      { stationId: "bustan-e-laleh", status: "operational" },
      { stationId: "meydan-e-hazrat-vali-asr", status: "operational" },
      { stationId: "maryam-e-moghaddas", status: "operational" },
      { stationId: "shohada-ye-haftom-e-tir", status: "operational" },
      { stationId: "bahar-shiraz-khanevadeh-hospital", status: "operational" },
      { stationId: "sarbaz", status: "operational" },
      { stationId: "imam-hossein", status: "operational" },
      { stationId: "meydan-e-shohada", status: "operational" },
      { stationId: "amirkabir", status: "operational" },
      { stationId: "shohada-ye-hefdah-e-shahrivar", status: "operational" },
      { stationId: "meydan-e-khorasan", status: "operational" },
      { stationId: "shahid-rezaei", status: "operational" },
      { stationId: "besat", status: "operational" },
      { stationId: "kiyan-shahr", status: "operational" },
      { stationId: "shohada-ye-dowlat-abad", status: "operational" },
      { stationId: "cheshmeh-ali", status: "operational" },
      { stationId: "ebn-e-babviyeh", status: "operational" },
      { stationId: "meydan-e-hazrat-e-abdol-azim", status: "operational" },
      { stationId: "haram-e-hazrat-e-abdol-azim", status: "operational" },
    ],
  },
  {
    id: "line-7-main",
    lineId: 7,
    stops: [
      { stationId: "varzeshgah-e-takhti", status: "operational" },
      { stationId: "basij", status: "operational" },
      { stationId: "ahang", status: "operational" },
      { stationId: "chehel-tan-e-doulab", status: "operational" },
      { stationId: "shohada-ye-hefdah-e-shahrivar", status: "operational" },
      { stationId: "meydan-e-giyam", status: "operational" },
      { stationId: "mowlavi", status: "operational" },
      { stationId: "meydan-e-mohammadiyeh", status: "operational" },
      { stationId: "mahdiyeh", status: "operational" },
      { stationId: "helal-ahmar", status: "operational" },
      { stationId: "beryanak", status: "operational" },
      { stationId: "komeyl", status: "operational" },
      { stationId: "roudaki", status: "operational" },
      { stationId: "shahid-navab-e-safavi", status: "operational" },
      { stationId: "towhid", status: "operational" },
      { stationId: "modafean-e-salamat", status: "operational" },
      { stationId: "daneshgah-e-tarbiat-modarres", status: "operational" },
      { stationId: "boostan-e-goftegou", status: "operational" },
      { stationId: "milad-tower", status: "operational" },
      { stationId: "meydan-e-sanat", status: "operational" },
      { stationId: "shahid-dadman", status: "operational" },
      { stationId: "meydan-e-ketab", status: "operational" },
    ],
  },
];
