// Network edges, generated from ROUTES consecutive pairs (see routes.ts).
// Track status is INDEPENDENT from station status: every segment defaults to
// operational; under-construction tracks are listed explicitly in
// SEGMENT_STATUS_OVERRIDES. A non-boardable station (e.g. Vavan) does NOT
// make its tracks non-operational — trains pass through.
import type { MetroSegment, SegmentId, SegmentStatus } from "./types";

export const SEGMENT_STATUS_OVERRIDES: Partial<Record<SegmentId, SegmentStatus>> = {
  "line-4-allameh-jafari-ayatollah-kashani": "under_construction",
  "line-4-ayatollah-kashani-chaharbagh": "under_construction",
  "line-6-cheshmeh-ali-ebn-e-babviyeh": "under_construction",
  "line-6-ebn-e-babviyeh-meydan-e-hazrat-e-abdol-azim": "under_construction",
  "line-6-meydan-e-hazrat-e-abdol-azim-haram-e-hazrat-e-abdol-azim": "under_construction",
  "line-6-shohada-ye-dowlat-abad-cheshmeh-ali": "under_construction",
};

function seg(
  id: SegmentId, lineId: number, routeId: string, from: string, to: string,
  branchId?: string,
): MetroSegment {
  const status: SegmentStatus = SEGMENT_STATUS_OVERRIDES[id] ?? "operational";
  return branchId
    ? { id, lineId, routeId, branchId, from, to, status }
    : { id, lineId, routeId, from, to, status };
}

export const SEGMENTS: MetroSegment[] = [
  seg("line-1-tajrish-gheytariyeh", 1, "line-1-main", "tajrish", "gheytariyeh"),
  seg("line-1-gheytariyeh-shahid-sadr", 1, "line-1-main", "gheytariyeh", "shahid-sadr"),
  seg("line-1-shahid-sadr-qolhak", 1, "line-1-main", "shahid-sadr", "qolhak"),
  seg("line-1-qolhak-doctor-shariati", 1, "line-1-main", "qolhak", "doctor-shariati"),
  seg("line-1-doctor-shariati-mirdamad", 1, "line-1-main", "doctor-shariati", "mirdamad"),
  seg("line-1-mirdamad-shahid-haghani", 1, "line-1-main", "mirdamad", "shahid-haghani"),
  seg("line-1-shahid-haghani-shahid-hemmat", 1, "line-1-main", "shahid-haghani", "shahid-hemmat"),
  seg("line-1-shahid-hemmat-mosalla-ye-imam-khomeini", 1, "line-1-main", "shahid-hemmat", "mosalla-ye-imam-khomeini"),
  seg("line-1-mosalla-ye-imam-khomeini-shahid-beheshti", 1, "line-1-main", "mosalla-ye-imam-khomeini", "shahid-beheshti"),
  seg("line-1-shahid-beheshti-shahid-mofattah", 1, "line-1-main", "shahid-beheshti", "shahid-mofattah"),
  seg("line-1-shahid-mofattah-shohada-ye-haftom-e-tir", 1, "line-1-main", "shahid-mofattah", "shohada-ye-haftom-e-tir"),
  seg("line-1-shohada-ye-haftom-e-tir-ayatollah-taleghani", 1, "line-1-main", "shohada-ye-haftom-e-tir", "ayatollah-taleghani"),
  seg("line-1-ayatollah-taleghani-darvazeh-dolat", 1, "line-1-main", "ayatollah-taleghani", "darvazeh-dolat"),
  seg("line-1-darvazeh-dolat-saadi", 1, "line-1-main", "darvazeh-dolat", "saadi"),
  seg("line-1-saadi-imam-khomeini", 1, "line-1-main", "saadi", "imam-khomeini"),
  seg("line-1-imam-khomeini-panzdah-e-khordad", 1, "line-1-main", "imam-khomeini", "panzdah-e-khordad"),
  seg("line-1-panzdah-e-khordad-khayyam", 1, "line-1-main", "panzdah-e-khordad", "khayyam"),
  seg("line-1-khayyam-meydan-e-mohammadiyeh", 1, "line-1-main", "khayyam", "meydan-e-mohammadiyeh"),
  seg("line-1-meydan-e-mohammadiyeh-shoush", 1, "line-1-main", "meydan-e-mohammadiyeh", "shoush"),
  seg("line-1-shoush-payaneh-jonoub-jonoub-terminal", 1, "line-1-main", "shoush", "payaneh-jonoub-jonoub-terminal"),
  seg("line-1-payaneh-jonoub-jonoub-terminal-shahid-bokharaei", 1, "line-1-main", "payaneh-jonoub-jonoub-terminal", "shahid-bokharaei"),
  seg("line-1-shahid-bokharaei-aliabad", 1, "line-1-main", "shahid-bokharaei", "aliabad"),
  seg("line-1-aliabad-javanmard-e-ghassab", 1, "line-1-main", "aliabad", "javanmard-e-ghassab"),
  seg("line-1-javanmard-e-ghassab-shahr-e-rey", 1, "line-1-main", "javanmard-e-ghassab", "shahr-e-rey"),
  seg("line-1-shahr-e-rey-palayeshgah", 1, "line-1-main", "shahr-e-rey", "palayeshgah"),
  seg("line-1-palayeshgah-shahed-baghershahr", 1, "line-1-main", "palayeshgah", "shahed-baghershahr"),
  seg("line-1-shahed-baghershahr-holy-shrine-of-imam-khomeini", 1, "line-1-main", "shahed-baghershahr", "holy-shrine-of-imam-khomeini"),
  seg("line-1-holy-shrine-of-imam-khomeini-kahrizak", 1, "line-1-main", "holy-shrine-of-imam-khomeini", "kahrizak"),
  seg("line-1-shahed-baghershahr-namayeshgah-e-shahr-e-aftab", 1, "line-1-parand", "shahed-baghershahr", "namayeshgah-e-shahr-e-aftab","parand"),
  seg("line-1-namayeshgah-e-shahr-e-aftab-vavan", 1, "line-1-parand", "namayeshgah-e-shahr-e-aftab", "vavan","parand"),
  seg("line-1-vavan-emam-khomeini-airport", 1, "line-1-parand", "vavan", "emam-khomeini-airport","parand"),
  seg("line-1-emam-khomeini-airport-shahr-e-parand", 1, "line-1-parand", "emam-khomeini-airport", "shahr-e-parand","parand"),
  seg("line-2-farhangsara-tehranpars", 2, "line-2-main", "farhangsara", "tehranpars"),
  seg("line-2-tehranpars-shahid-bagheri", 2, "line-2-main", "tehranpars", "shahid-bagheri"),
  seg("line-2-shahid-bagheri-daneshgah-e-elm-o-sanat", 2, "line-2-main", "shahid-bagheri", "daneshgah-e-elm-o-sanat"),
  seg("line-2-daneshgah-e-elm-o-sanat-sarsabz", 2, "line-2-main", "daneshgah-e-elm-o-sanat", "sarsabz"),
  seg("line-2-sarsabz-janbazan", 2, "line-2-main", "sarsabz", "janbazan"),
  seg("line-2-janbazan-fadak", 2, "line-2-main", "janbazan", "fadak"),
  seg("line-2-fadak-sabalan", 2, "line-2-main", "fadak", "sabalan"),
  seg("line-2-sabalan-shahid-madani", 2, "line-2-main", "sabalan", "shahid-madani"),
  seg("line-2-shahid-madani-imam-hossein", 2, "line-2-main", "shahid-madani", "imam-hossein"),
  seg("line-2-imam-hossein-darvazeh-shemiran", 2, "line-2-main", "imam-hossein", "darvazeh-shemiran"),
  seg("line-2-darvazeh-shemiran-baharistan", 2, "line-2-main", "darvazeh-shemiran", "baharistan"),
  seg("line-2-baharistan-mellat", 2, "line-2-main", "baharistan", "mellat"),
  seg("line-2-mellat-imam-khomeini", 2, "line-2-main", "mellat", "imam-khomeini"),
  seg("line-2-imam-khomeini-hasan-abad", 2, "line-2-main", "imam-khomeini", "hasan-abad"),
  seg("line-2-hasan-abad-daneshgah-e-imam-ali", 2, "line-2-main", "hasan-abad", "daneshgah-e-imam-ali"),
  seg("line-2-daneshgah-e-imam-ali-meydan-e-horr", 2, "line-2-main", "daneshgah-e-imam-ali", "meydan-e-horr"),
  seg("line-2-meydan-e-horr-shahid-navab-e-safavi", 2, "line-2-main", "meydan-e-horr", "shahid-navab-e-safavi"),
  seg("line-2-shahid-navab-e-safavi-shademan", 2, "line-2-main", "shahid-navab-e-safavi", "shademan"),
  seg("line-2-shademan-daneshgah-e-sharif", 2, "line-2-main", "shademan", "daneshgah-e-sharif"),
  seg("line-2-daneshgah-e-sharif-tarasht", 2, "line-2-main", "daneshgah-e-sharif", "tarasht"),
  seg("line-2-tarasht-tehran-sadeghiyeh", 2, "line-2-main", "tarasht", "tehran-sadeghiyeh"),
  seg("line-3-qaem-shahid-mahallati", 3, "line-3-main", "qaem", "shahid-mahallati"),
  seg("line-3-shahid-mahallati-aghdasiyeh", 3, "line-3-main", "shahid-mahallati", "aghdasiyeh"),
  seg("line-3-aghdasiyeh-nobonyad", 3, "line-3-main", "aghdasiyeh", "nobonyad"),
  seg("line-3-nobonyad-hossein-abad", 3, "line-3-main", "nobonyad", "hossein-abad"),
  seg("line-3-hossein-abad-meydan-e-heravi", 3, "line-3-main", "hossein-abad", "meydan-e-heravi"),
  seg("line-3-meydan-e-heravi-shahid-zeynoddin", 3, "line-3-main", "meydan-e-heravi", "shahid-zeynoddin"),
  seg("line-3-shahid-zeynoddin-khajeh-abdollah-e-ansari", 3, "line-3-main", "shahid-zeynoddin", "khajeh-abdollah-e-ansari"),
  seg("line-3-khajeh-abdollah-e-ansari-shahid-sayyad-shirazi", 3, "line-3-main", "khajeh-abdollah-e-ansari", "shahid-sayyad-shirazi"),
  seg("line-3-shahid-sayyad-shirazi-shahid-ghodousi", 3, "line-3-main", "shahid-sayyad-shirazi", "shahid-ghodousi"),
  seg("line-3-shahid-ghodousi-sohrevardi", 3, "line-3-main", "shahid-ghodousi", "sohrevardi"),
  seg("line-3-sohrevardi-shahid-beheshti", 3, "line-3-main", "sohrevardi", "shahid-beheshti"),
  seg("line-3-shahid-beheshti-mirza-ye-shirazi", 3, "line-3-main", "shahid-beheshti", "mirza-ye-shirazi"),
  seg("line-3-mirza-ye-shirazi-meydan-e-jahad", 3, "line-3-main", "mirza-ye-shirazi", "meydan-e-jahad"),
  seg("line-3-meydan-e-jahad-meydan-e-hazrat-vali-asr", 3, "line-3-main", "meydan-e-jahad", "meydan-e-hazrat-vali-asr"),
  seg("line-3-meydan-e-hazrat-vali-asr-teatr-e-shahr", 3, "line-3-main", "meydan-e-hazrat-vali-asr", "teatr-e-shahr"),
  seg("line-3-teatr-e-shahr-moniriyeh", 3, "line-3-main", "teatr-e-shahr", "moniriyeh"),
  seg("line-3-moniriyeh-mahdiyeh", 3, "line-3-main", "moniriyeh", "mahdiyeh"),
  seg("line-3-mahdiyeh-rahahan", 3, "line-3-main", "mahdiyeh", "rahahan"),
  seg("line-3-rahahan-javadiyeh", 3, "line-3-main", "rahahan", "javadiyeh"),
  seg("line-3-javadiyeh-zamzam", 3, "line-3-main", "javadiyeh", "zamzam"),
  seg("line-3-zamzam-shahrak-e-shariaty", 3, "line-3-main", "zamzam", "shahrak-e-shariaty"),
  seg("line-3-shahrak-e-shariaty-abdol-abad", 3, "line-3-main", "shahrak-e-shariaty", "abdol-abad"),
  seg("line-3-abdol-abad-nemat-abad", 3, "line-3-main", "abdol-abad", "nemat-abad"),
  seg("line-3-nemat-abad-azadegan", 3, "line-3-main", "nemat-abad", "azadegan"),
  seg("line-4-shahid-kolahdooz-nirou-havaei", 4, "line-4-main", "shahid-kolahdooz", "nirou-havaei"),
  seg("line-4-nirou-havaei-nabard", 4, "line-4-main", "nirou-havaei", "nabard"),
  seg("line-4-nabard-piroozi", 4, "line-4-main", "nabard", "piroozi"),
  seg("line-4-piroozi-ebn-e-sina", 4, "line-4-main", "piroozi", "ebn-e-sina"),
  seg("line-4-ebn-e-sina-meydan-e-shohada", 4, "line-4-main", "ebn-e-sina", "meydan-e-shohada"),
  seg("line-4-meydan-e-shohada-darvazeh-shemiran", 4, "line-4-main", "meydan-e-shohada", "darvazeh-shemiran"),
  seg("line-4-darvazeh-shemiran-darvazeh-dolat", 4, "line-4-main", "darvazeh-shemiran", "darvazeh-dolat"),
  seg("line-4-darvazeh-dolat-ferdowsi", 4, "line-4-main", "darvazeh-dolat", "ferdowsi"),
  seg("line-4-ferdowsi-teatr-e-shahr", 4, "line-4-main", "ferdowsi", "teatr-e-shahr"),
  seg("line-4-teatr-e-shahr-meydan-e-enghelab-e-eslami", 4, "line-4-main", "teatr-e-shahr", "meydan-e-enghelab-e-eslami"),
  seg("line-4-meydan-e-enghelab-e-eslami-towhid", 4, "line-4-main", "meydan-e-enghelab-e-eslami", "towhid"),
  seg("line-4-towhid-shademan", 4, "line-4-main", "towhid", "shademan"),
  seg("line-4-shademan-doctor-habibollah", 4, "line-4-main", "shademan", "doctor-habibollah"),
  seg("line-4-doctor-habibollah-ostad-moin", 4, "line-4-main", "doctor-habibollah", "ostad-moin"),
  seg("line-4-ostad-moin-meydan-e-azadi", 4, "line-4-main", "ostad-moin", "meydan-e-azadi"),
  seg("line-4-meydan-e-azadi-bimeh", 4, "line-4-main", "meydan-e-azadi", "bimeh"),
  seg("line-4-bimeh-shahrak-e-ekbatan", 4, "line-4-main", "bimeh", "shahrak-e-ekbatan"),
  seg("line-4-shahrak-e-ekbatan-eram-e-sabz", 4, "line-4-main", "shahrak-e-ekbatan", "eram-e-sabz"),
  seg("line-4-eram-e-sabz-allameh-jafari", 4, "line-4-main", "eram-e-sabz", "allameh-jafari"),
  seg("line-4-allameh-jafari-ayatollah-kashani", 4, "line-4-main", "allameh-jafari", "ayatollah-kashani"),
  seg("line-4-ayatollah-kashani-chaharbagh", 4, "line-4-main", "ayatollah-kashani", "chaharbagh"),
  seg("line-4-bimeh-mehrabad-airport-terminal-1-2", 4, "line-4-mehrabad", "bimeh", "mehrabad-airport-terminal-1-2","mehrabad"),
  seg("line-4-mehrabad-airport-terminal-1-2-mehrabad-airport-terminal-4-6", 4, "line-4-mehrabad", "mehrabad-airport-terminal-1-2", "mehrabad-airport-terminal-4-6","mehrabad"),
  seg("line-5-tehran-sadeghiyeh-eram-e-sabz", 5, "line-5-main", "tehran-sadeghiyeh", "eram-e-sabz"),
  seg("line-5-eram-e-sabz-varzeshgah-e-azadi", 5, "line-5-main", "eram-e-sabz", "varzeshgah-e-azadi"),
  seg("line-5-varzeshgah-e-azadi-chitgar", 5, "line-5-main", "varzeshgah-e-azadi", "chitgar"),
  seg("line-5-chitgar-iran-khodro", 5, "line-5-main", "chitgar", "iran-khodro"),
  seg("line-5-iran-khodro-vardavard", 5, "line-5-main", "iran-khodro", "vardavard"),
  seg("line-5-vardavard-garmdareh", 5, "line-5-main", "vardavard", "garmdareh"),
  seg("line-5-garmdareh-atmosphere", 5, "line-5-main", "garmdareh", "atmosphere"),
  seg("line-5-atmosphere-karaj", 5, "line-5-main", "atmosphere", "karaj"),
  seg("line-5-karaj-mohammadshahr", 5, "line-5-main", "karaj", "mohammadshahr"),
  seg("line-5-mohammadshahr-golshahr", 5, "line-5-main", "mohammadshahr", "golshahr"),
  seg("line-5-golshahr-shahid-fakhrizadeh", 5, "line-5-main", "golshahr", "shahid-fakhrizadeh"),
  seg("line-5-shahid-fakhrizadeh-shahid-sepahbod-qasem-soleimani", 5, "line-5-main", "shahid-fakhrizadeh", "shahid-sepahbod-qasem-soleimani"),
  seg("line-6-kouhsar-shohada-ye-kan", 6, "line-6-main", "kouhsar", "shohada-ye-kan"),
  seg("line-6-shohada-ye-kan-shahran", 6, "line-6-main", "shohada-ye-kan", "shahran"),
  seg("line-6-shahran-shahr-e-ziba", 6, "line-6-main", "shahran", "shahr-e-ziba"),
  seg("line-6-shahr-e-ziba-ayatollah-kashani", 6, "line-6-main", "shahr-e-ziba", "ayatollah-kashani"),
  seg("line-6-ayatollah-kashani-shahid-sattari", 6, "line-6-main", "ayatollah-kashani", "shahid-sattari"),
  seg("line-6-shahid-sattari-shahid-ashrafi-esfahani", 6, "line-6-main", "shahid-sattari", "shahid-ashrafi-esfahani"),
  seg("line-6-shahid-ashrafi-esfahani-yadegar-e-imam", 6, "line-6-main", "shahid-ashrafi-esfahani", "yadegar-e-imam"),
  seg("line-6-yadegar-e-imam-marzdaran", 6, "line-6-main", "yadegar-e-imam", "marzdaran"),
  seg("line-6-marzdaran-shahrak-e-azmayesh", 6, "line-6-main", "marzdaran", "shahrak-e-azmayesh"),
  seg("line-6-shahrak-e-azmayesh-daneshgah-e-tarbiat-modarres", 6, "line-6-main", "shahrak-e-azmayesh", "daneshgah-e-tarbiat-modarres"),
  seg("line-6-daneshgah-e-tarbiat-modarres-karagar", 6, "line-6-main", "daneshgah-e-tarbiat-modarres", "karagar"),
  seg("line-6-karagar-bustan-e-laleh", 6, "line-6-main", "karagar", "bustan-e-laleh"),
  seg("line-6-bustan-e-laleh-meydan-e-hazrat-vali-asr", 6, "line-6-main", "bustan-e-laleh", "meydan-e-hazrat-vali-asr"),
  seg("line-6-meydan-e-hazrat-vali-asr-maryam-e-moghaddas", 6, "line-6-main", "meydan-e-hazrat-vali-asr", "maryam-e-moghaddas"),
  seg("line-6-maryam-e-moghaddas-shohada-ye-haftom-e-tir", 6, "line-6-main", "maryam-e-moghaddas", "shohada-ye-haftom-e-tir"),
  seg("line-6-shohada-ye-haftom-e-tir-bahar-shiraz-khanevadeh-hospital", 6, "line-6-main", "shohada-ye-haftom-e-tir", "bahar-shiraz-khanevadeh-hospital"),
  seg("line-6-bahar-shiraz-khanevadeh-hospital-sarbaz", 6, "line-6-main", "bahar-shiraz-khanevadeh-hospital", "sarbaz"),
  seg("line-6-sarbaz-imam-hossein", 6, "line-6-main", "sarbaz", "imam-hossein"),
  seg("line-6-imam-hossein-meydan-e-shohada", 6, "line-6-main", "imam-hossein", "meydan-e-shohada"),
  seg("line-6-meydan-e-shohada-amirkabir", 6, "line-6-main", "meydan-e-shohada", "amirkabir"),
  seg("line-6-amirkabir-shohada-ye-hefdah-e-shahrivar", 6, "line-6-main", "amirkabir", "shohada-ye-hefdah-e-shahrivar"),
  seg("line-6-shohada-ye-hefdah-e-shahrivar-meydan-e-khorasan", 6, "line-6-main", "shohada-ye-hefdah-e-shahrivar", "meydan-e-khorasan"),
  seg("line-6-meydan-e-khorasan-shahid-rezaei", 6, "line-6-main", "meydan-e-khorasan", "shahid-rezaei"),
  seg("line-6-shahid-rezaei-besat", 6, "line-6-main", "shahid-rezaei", "besat"),
  seg("line-6-besat-kiyan-shahr", 6, "line-6-main", "besat", "kiyan-shahr"),
  seg("line-6-kiyan-shahr-shohada-ye-dowlat-abad", 6, "line-6-main", "kiyan-shahr", "shohada-ye-dowlat-abad"),
  seg("line-6-shohada-ye-dowlat-abad-cheshmeh-ali", 6, "line-6-main", "shohada-ye-dowlat-abad", "cheshmeh-ali"),
  seg("line-6-cheshmeh-ali-ebn-e-babviyeh", 6, "line-6-main", "cheshmeh-ali", "ebn-e-babviyeh"),
  seg("line-6-ebn-e-babviyeh-meydan-e-hazrat-e-abdol-azim", 6, "line-6-main", "ebn-e-babviyeh", "meydan-e-hazrat-e-abdol-azim"),
  seg("line-6-meydan-e-hazrat-e-abdol-azim-haram-e-hazrat-e-abdol-azim", 6, "line-6-main", "meydan-e-hazrat-e-abdol-azim", "haram-e-hazrat-e-abdol-azim"),
  seg("line-7-varzeshgah-e-takhti-basij", 7, "line-7-main", "varzeshgah-e-takhti", "basij"),
  seg("line-7-basij-ahang", 7, "line-7-main", "basij", "ahang"),
  seg("line-7-ahang-chehel-tan-e-doulab", 7, "line-7-main", "ahang", "chehel-tan-e-doulab"),
  seg("line-7-chehel-tan-e-doulab-shohada-ye-hefdah-e-shahrivar", 7, "line-7-main", "chehel-tan-e-doulab", "shohada-ye-hefdah-e-shahrivar"),
  seg("line-7-shohada-ye-hefdah-e-shahrivar-meydan-e-giyam", 7, "line-7-main", "shohada-ye-hefdah-e-shahrivar", "meydan-e-giyam"),
  seg("line-7-meydan-e-giyam-mowlavi", 7, "line-7-main", "meydan-e-giyam", "mowlavi"),
  seg("line-7-mowlavi-meydan-e-mohammadiyeh", 7, "line-7-main", "mowlavi", "meydan-e-mohammadiyeh"),
  seg("line-7-meydan-e-mohammadiyeh-mahdiyeh", 7, "line-7-main", "meydan-e-mohammadiyeh", "mahdiyeh"),
  seg("line-7-mahdiyeh-helal-ahmar", 7, "line-7-main", "mahdiyeh", "helal-ahmar"),
  seg("line-7-helal-ahmar-beryanak", 7, "line-7-main", "helal-ahmar", "beryanak"),
  seg("line-7-beryanak-komeyl", 7, "line-7-main", "beryanak", "komeyl"),
  seg("line-7-komeyl-roudaki", 7, "line-7-main", "komeyl", "roudaki"),
  seg("line-7-roudaki-shahid-navab-e-safavi", 7, "line-7-main", "roudaki", "shahid-navab-e-safavi"),
  seg("line-7-shahid-navab-e-safavi-towhid", 7, "line-7-main", "shahid-navab-e-safavi", "towhid"),
  seg("line-7-towhid-modafean-e-salamat", 7, "line-7-main", "towhid", "modafean-e-salamat"),
  seg("line-7-modafean-e-salamat-daneshgah-e-tarbiat-modarres", 7, "line-7-main", "modafean-e-salamat", "daneshgah-e-tarbiat-modarres"),
  seg("line-7-daneshgah-e-tarbiat-modarres-boostan-e-goftegou", 7, "line-7-main", "daneshgah-e-tarbiat-modarres", "boostan-e-goftegou"),
  seg("line-7-boostan-e-goftegou-milad-tower", 7, "line-7-main", "boostan-e-goftegou", "milad-tower"),
  seg("line-7-milad-tower-meydan-e-sanat", 7, "line-7-main", "milad-tower", "meydan-e-sanat"),
  seg("line-7-meydan-e-sanat-shahid-dadman", 7, "line-7-main", "meydan-e-sanat", "shahid-dadman"),
  seg("line-7-shahid-dadman-meydan-e-ketab", 7, "line-7-main", "shahid-dadman", "meydan-e-ketab"),
];
