// Auto-generated from lib/metro-data.ts (upstream: tehran-metro-data, mostafa-kheibary).
// Do not edit by hand. Stable kebab-case IDs; display names preserved verbatim.
// Status mapping: upstream disabled:true -> under_construction, EXCEPT
// shohada-ye-hefdah-e-shahrivar which is a live L6/L7 interchange (see docs).
import type { MetroStation } from "./types";

export const STATIONS: MetroStation[] = [
  {
    id: "tajrish",
    name: { fa: "تجریش", en: "Tajrish" },
    location: { lat: 35.804501, lng: 51.433643000000004 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "gheytariyeh",
    name: { fa: "قیطریه", en: "Gheytariyeh" },
    location: { lat: 35.793119, lng: 51.435252 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "shahid-sadr",
    name: { fa: "شهید صدر", en: "Shahid Sadr" },
    location: { lat: 35.785374, lng: 51.435639 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "qolhak",
    name: { fa: "قلهک", en: "Qolhak" },
    location: { lat: 35.7726822, lng: 51.4379137 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "doctor-shariati",
    name: { fa: "دکتر شریعتی", en: "Doctor Shariati" },
    location: { lat: 35.7626452, lng: 51.4440981 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "mirdamad",
    name: { fa: "میرداماد", en: "Mirdamad" },
    location: { lat: 35.76006, lng: 51.43375 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-haghani",
    name: { fa: "شهید حقانی", en: "Shahid Haghani" },
    location: { lat: 35.7565207, lng: 51.4257773 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-hemmat",
    name: { fa: "شهید همت", en: "Shahid Hemmat" },
    location: { lat: 35.748228, lng: 51.427372 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "mosalla-ye-imam-khomeini",
    name: { fa: "مصلی امام خمینی", en: "Mosalla-ye Imam Khomeini" },
    location: { lat: 35.74073, lng: 51.427082 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-beheshti",
    name: { fa: "شهید بهشتی", en: "Shahid Beheshti" },
    location: { lat: 35.731037, lng: 51.42704 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: true, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-mofattah",
    name: { fa: "شهید مفتح", en: "Shahid Mofattah" },
    location: { lat: 35.724453, lng: 51.427632 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "ayatollah-taleghani",
    name: { fa: "آیت‌الله طالقانی", en: "Ayatollah Taleghani" },
    location: { lat: 35.707161, lng: 51.425495 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "darvazeh-dolat",
    name: { fa: "دروازه دولت", en: "Darvazeh Dolat" },
    location: { lat: 35.701316, lng: 51.425849 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: true, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "saadi",
    name: { fa: "سعدی", en: "Sa'adi" },
    location: { lat: 35.6934793, lng: 51.4244163 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "imam-khomeini",
    name: { fa: "امام خمینی", en: "Imam Khomeini" },
    location: { lat: 35.686433, lng: 51.421171 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: true, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "panzdah-e-khordad",
    name: { fa: "پانزده خرداد", en: "Panzdah-e Khordad" },
    location: { lat: 35.678276, lng: 51.417287 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "khayyam",
    name: { fa: "خیام", en: "Khayyam" },
    location: { lat: 35.673073, lng: 51.416568 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "meydan-e-mohammadiyeh",
    name: { fa: "میدان محمدیه", en: "Meydan-e Mohammadiyeh" },
    location: { lat: 35.667753, lng: 51.415488 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "shoush",
    name: { fa: "شوش", en: "Shoush" },
    location: { lat: 35.65754, lng: 51.414154 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "payaneh-jonoub-jonoub-terminal",
    name: { fa: "پایانه جنوبی", en: "Payaneh Jonoub(Jonoub Terminal)" },
    location: { lat: 35.650688, lng: 51.416289 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-bokharaei",
    name: { fa: "شهید بخارایی", en: "Shahid Bokharaei" },
    location: { lat: 35.640609, lng: 51.414787 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "aliabad",
    name: { fa: "علی‌آباد", en: "Aliabad" },
    location: { lat: 35.629256, lng: 51.416203 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "javanmard-e-ghassab",
    name: { fa: "جوانمرد قصاب", en: "Javanmard-e Ghassab" },
    location: { lat: 35.609764, lng: 51.420141 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "shahr-e-rey",
    name: { fa: "شهر ری", en: "Shahr-e Rey" },
    location: { lat: 35.594672, lng: 51.422287 },
    amenities: { wc: true, elevator: true, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "palayeshgah",
    name: { fa: "پالایشگاه", en: "Palayeshgah" },
    location: { lat: 35.57357, lng: 51.406975 },
    amenities: { wc: true, elevator: false, atm: true, coffeeShop: true, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahed-baghershahr",
    name: { fa: "شاهد - باقرشهر", en: "Shahed - BagherShahr" },
    location: { lat: 35.546998, lng: 51.382606 },
    amenities: { wc: false, elevator: false, atm: true, coffeeShop: false, fastFood: false, groceryStore: true, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "namayeshgah-e-shahr-e-aftab",
    name: { fa: "نمایشگاه شهر آفتاب", en: "Namayeshgah-e Shahr-e Aftab" },
    location: { lat: 35.539811, lng: 51.349032 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "vavan",
    name: { fa: "واوان", en: "Vavan" },
    location: { lat: 35.514507, lng: 51.30011 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "under_construction",
  },
  {
    id: "emam-khomeini-airport",
    name: { fa: "فرودگاه امام خمینی", en: "Emam Khomeini Airport" },
    location: { lat: 35.416111, lng: 51.152221 },
    amenities: { wc: true, elevator: true, atm: true, coffeeShop: true, fastFood: true, groceryStore: true, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahr-e-parand",
    name: { fa: "شهر پرند", en: "Shahr-e Parand" },
    location: { lat: 35.489058, lng: 50.923976 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "holy-shrine-of-imam-khomeini",
    name: { fa: "حرم مطهر امام خمینی", en: "Holy Shrine of Imam Khomeini" },
    location: { lat: 35.545077, lng: 51.373036 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "kahrizak",
    name: { fa: "کهریزک", en: "Kahrizak" },
    location: { lat: 35.521574, lng: 51.369292 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "farhangsara",
    name: { fa: "فرهنگسرا", en: "Farhangsara" },
    location: { lat: 35.729687, lng: 51.546757 },
    amenities: { wc: false, elevator: false, atm: true, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "tehranpars",
    name: { fa: "تهرانپارس", en: "Tehranpars" },
    location: { lat: 35.7316491, lng: 51.5285321 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-bagheri",
    name: { fa: "شهید باقری", en: "Shahid Bagheri" },
    location: { lat: 35.733397, lng: 51.516856 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: true, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "daneshgah-e-elm-o-sanat",
    name: { fa: "دانشگاه علم و صنعت", en: "Daneshgah-e Elm-o San'at" },
    location: { lat: 35.734425, lng: 51.504786 },
    amenities: { wc: true, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "sarsabz",
    name: { fa: "سرسبز", en: "Sarsabz" },
    location: { lat: 35.73547, lng: 51.494873 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "janbazan",
    name: { fa: "جانبازان", en: "Janbazan" },
    location: { lat: 35.733088, lng: 51.484081 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "fadak",
    name: { fa: "فدک", en: "Fadak" },
    location: { lat: 35.7264805, lng: 51.4756353 },
    amenities: { wc: false, elevator: false, atm: true, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "sabalan",
    name: { fa: "سبلان", en: "Sabalan" },
    location: { lat: 35.71826, lng: 51.464531 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-madani",
    name: { fa: "شهید مدنی", en: "Shahid Madani" },
    location: { lat: 35.70913, lng: 51.453459 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "imam-hossein",
    name: { fa: "امام حسین", en: "Imam Hossein" },
    location: { lat: 35.702188, lng: 51.445702 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "darvazeh-shemiran",
    name: { fa: "دروازه شمیران", en: "Darvazeh Shemiran" },
    location: { lat: 35.699338, lng: 51.437709 },
    amenities: { wc: false, elevator: false, atm: true, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "baharistan",
    name: { fa: "بهارستان", en: "Baharistan" },
    location: { lat: 35.692263, lng: 51.432946 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "mellat",
    name: { fa: "ملت", en: "Mellat" },
    location: { lat: 35.6889986, lng: 51.4277635 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "hasan-abad",
    name: { fa: "حسن آباد", en: "Hasan Abad" },
    location: { lat: 35.6863779, lng: 51.4088914 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "daneshgah-e-imam-ali",
    name: { fa: "دانشگاه امام علی", en: "Daneshgah-e Imam Ali" },
    location: { lat: 35.6874007, lng: 51.3990645 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "meydan-e-horr",
    name: { fa: "میدان حر", en: "Meydan-e Horr" },
    location: { lat: 35.691008, lng: 51.3884 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "shahid-navab-e-safavi",
    name: { fa: "شهید نواب صفوی", en: "Shahid Navab-e Safavi" },
    location: { lat: 35.69526, lng: 51.378229 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "shademan",
    name: { fa: "شادمان", en: "Shademan" },
    location: { lat: 35.700627, lng: 51.363809 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "daneshgah-e-sharif",
    name: { fa: "دانشگاه شریف", en: "Daneshgah-e Sharif" },
    location: { lat: 35.70575, lng: 51.353638 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "tarasht",
    name: { fa: "طرشت", en: "Tarasht" },
    location: { lat: 35.716134, lng: 51.34351 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "tehran-sadeghiyeh",
    name: { fa: "تهران (صادقیه)", en: "Tehran (Sadeghiyeh)" },
    location: { lat: 35.717598, lng: 51.330979 },
    amenities: { wc: true, elevator: true, atm: false, coffeeShop: false, fastFood: true, groceryStore: true, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "qaem",
    name: { fa: "قائم", en: "Qa'em" },
    location: { lat: 35.799759, lng: 51.521684 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-mahallati",
    name: { fa: "شهید محلاتی", en: "Shahid Mahallati" },
    location: { lat: 35.797925, lng: 51.508169 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "aghdasiyeh",
    name: { fa: "اقدسیه", en: "Aghdasiyeh" },
    location: { lat: 35.795958, lng: 51.493566 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "nobonyad",
    name: { fa: "نوبنیاد", en: "Nobonyad" },
    location: { lat: 35.790987, lng: 51.478029 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "hossein-abad",
    name: { fa: "حسین‌آباد", en: "Hossein Abad" },
    location: { lat: 35.779428, lng: 51.47852 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "meydan-e-heravi",
    name: { fa: "میدان هروی", en: "Meydan-e Heravi" },
    location: { lat: 35.771831, lng: 51.473219 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-zeynoddin",
    name: { fa: "شهید زین‌الدین", en: "Shahid Zeynoddin" },
    location: { lat: 35.7595603, lng: 51.4659032 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "khajeh-abdollah-e-ansari",
    name: { fa: "خواجه عبدالله انصاری", en: "Khajeh Abdollah-e Ansari" },
    location: { lat: 35.743739, lng: 51.462922 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "shahid-sayyad-shirazi",
    name: { fa: "شهید صیاد شیرازی", en: "Shahid Sayyad Shirazi" },
    location: { lat: 35.735349, lng: 51.458594 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-ghodousi",
    name: { fa: "شهید قدوسی", en: "Shahid Ghodousi" },
    location: { lat: 35.731553, lng: 51.4445 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "sohrevardi",
    name: { fa: "سهروردی", en: "Sohrevardi" },
    location: { lat: 35.731066, lng: 51.435852 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "mirza-ye-shirazi",
    name: { fa: "میرزا شیرازی", en: "Mirza-ye Shirazi" },
    location: { lat: 35.728365, lng: 51.417448 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "meydan-e-jahad",
    name: { fa: "میدان جهاد", en: "Meydan-e Jahad" },
    location: { lat: 35.721672, lng: 51.408803 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "teatr-e-shahr",
    name: { fa: "تئاتر شهر", en: "Teatr-e Shahr" },
    location: { lat: 35.700954, lng: 51.405831 },
    amenities: { wc: false, elevator: false, atm: true, coffeeShop: true, fastFood: true, groceryStore: true, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "moniriyeh",
    name: { fa: "منیریه", en: "Moniriyeh" },
    location: { lat: 35.681087, lng: 51.401594 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "mahdiyeh",
    name: { fa: "مهدیه", en: "Mahdiyeh" },
    location: { lat: 35.671463, lng: 51.405474 },
    amenities: { wc: true, elevator: false, atm: true, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "rahahan",
    name: { fa: "راه آهن", en: "Rahahan" },
    location: { lat: 35.6595573, lng: 51.3984659 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "javadiyeh",
    name: { fa: "جوادیه", en: "Javadiyeh" },
    location: { lat: 35.659075, lng: 51.388215 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "zamzam",
    name: { fa: "زمزم", en: "Zamzam" },
    location: { lat: 35.6525844, lng: 51.3733202 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "shahrak-e-shariaty",
    name: { fa: "شهرک شریعتی", en: "Shahrak-e Shariaty" },
    location: { lat: 35.6435696, lng: 51.3677387 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "abdol-abad",
    name: { fa: "عبدل آباد", en: "Abdol Abad" },
    location: { lat: 35.638159, lng: 51.359773 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "nemat-abad",
    name: { fa: "نعمت آباد", en: "Nemat Abad" },
    location: { lat: 35.63392, lng: 51.34703 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "azadegan",
    name: { fa: "آزادگان", en: "Azadegan" },
    location: { lat: 35.627216, lng: 51.335533 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "shahid-kolahdooz",
    name: { fa: "شهید کلاهدوز", en: "Shahid Kolahdooz" },
    location: { lat: 35.698954, lng: 51.498563 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "nirou-havaei",
    name: { fa: "نیروهوایی", en: "Nirou Havaei" },
    location: { lat: 35.6926988, lng: 51.4886226 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "nabard",
    name: { fa: "نبرد", en: "Nabard" },
    location: { lat: 35.6913253, lng: 51.4777301 },
    amenities: { wc: false, elevator: false, atm: true, coffeeShop: false, fastFood: false, groceryStore: true, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "piroozi",
    name: { fa: "پیروزی", en: "Piroozi" },
    location: { lat: 35.691356, lng: 51.46775 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "ebn-e-sina",
    name: { fa: "ابن سینا", en: "Ebn-e Sina" },
    location: { lat: 35.6907927, lng: 51.4579435 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "ferdowsi",
    name: { fa: "فردوسی", en: "Ferdowsi" },
    location: { lat: 35.701255, lng: 51.418569 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "meydan-e-enghelab-e-eslami",
    name: { fa: "میدان انقلاب اسلامی", en: "Meydan-e Enghelab-e Eslami" },
    location: { lat: 35.701255, lng: 51.392176 },
    amenities: { wc: false, elevator: false, atm: true, coffeeShop: true, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "towhid",
    name: { fa: "توحید", en: "Towhid" },
    location: { lat: 35.700767, lng: 51.378572 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "doctor-habibollah",
    name: { fa: "دکتر حبیب‌الله", en: "Doctor Habibollah" },
    location: { lat: 35.700653, lng: 51.356079 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "ostad-moin",
    name: { fa: "استاد معین", en: "Ostad Mo'in" },
    location: { lat: 35.700131, lng: 51.34461 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "meydan-e-azadi",
    name: { fa: "میدان آزادی", en: "Meydan-e Azadi" },
    location: { lat: 35.700802, lng: 51.332492 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "bimeh",
    name: { fa: "بیمه", en: "Bimeh" },
    location: { lat: 35.699546, lng: 51.32036 },
    amenities: { wc: false, elevator: false, atm: true, coffeeShop: true, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "mehrabad-airport-terminal-1-2",
    name: { fa: "پایانه ۱ و ۲ فرودگاه مهرآباد", en: "Mehrabad Airport Terminal 1&2" },
    location: { lat: 35.690689, lng: 51.3196823 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "mehrabad-airport-terminal-4-6",
    name: { fa: "پایانه ۴ و ۶ فرودگاه مهرآباد", en: "Mehrabad Airport Terminal 4&6" },
    location: { lat: 35.6886266, lng: 51.3271795 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahrak-e-ekbatan",
    name: { fa: "شهرک اکباتان", en: "Shahrak-e Ekbatan" },
    location: { lat: 35.705557400000004, lng: 51.3074478 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "allameh-jafari",
    name: { fa: "علامه جعفری", en: "Allameh Jafari" },
    location: { lat: 35.73085963000432, lng: 51.30687773828286 },
    amenities: { wc: false, elevator: false, atm: true, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "chaharbagh",
    name: { fa: "چهارباغ", en: "Chaharbagh" },
    location: { lat: 35.7506525742434, lng: 51.30401221869391 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "under_construction",
  },
  {
    id: "eram-e-sabz",
    name: { fa: "ارم سبز", en: "Eram-e Sabz" },
    location: { lat: 35.717476, lng: 51.301979 },
    amenities: { wc: true, elevator: true, atm: true, coffeeShop: true, fastFood: true, groceryStore: true, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "varzeshgah-e-azadi",
    name: { fa: "ورزشگاه آزادی", en: "Varzeshgah-e Azadi" },
    location: { lat: 35.716727, lng: 51.281208 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "chitgar",
    name: { fa: "چیتگر", en: "Chitgar" },
    location: { lat: 35.717563, lng: 51.243904 },
    amenities: { wc: true, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "iran-khodro",
    name: { fa: "ایران‌خودرو", en: "Iran Khodro" },
    location: { lat: 35.725402, lng: 51.196654 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "vardavard",
    name: { fa: "وردآورد", en: "Vardavard" },
    location: { lat: 35.7444768, lng: 51.1509866 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "garmdareh",
    name: { fa: "گرم‌دره", en: "Garmdareh" },
    location: { lat: 35.751002, lng: 51.08193 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "atmosphere",
    name: { fa: "اتمسفر", en: "Atmosphere" },
    location: { lat: 35.7662914, lng: 51.0469759 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "karaj",
    name: { fa: "کرج", en: "Karaj" },
    location: { lat: 35.7870098, lng: 51.0026979 },
    amenities: { wc: true, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "mohammadshahr",
    name: { fa: "محمدشهر", en: "Mohammadshahr" },
    location: { lat: 35.800951, lng: 50.964729 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "golshahr",
    name: { fa: "گلشهر", en: "Golshahr" },
    location: { lat: 35.824877, lng: 50.933079 },
    amenities: { wc: true, elevator: true, atm: true, coffeeShop: true, fastFood: true, groceryStore: true, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "shahid-fakhrizadeh",
    name: { fa: "شهید فخری‌زاده", en: "Shahid Fakhrizadeh" },
    location: { lat: 35.91758, lng: 50.7911 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: false },
    amenitiesVerified: false,
    status: "operational",
  },
  {
    id: "shahid-sepahbod-qasem-soleimani",
    name: { fa: "شهید سپهبد قاسم سلیمانی", en: "Shahid Sepahbod Qasem Soleimani" },
    location: { lat: 35.8261, lng: 50.8881 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "haram-e-hazrat-e-abdol-azim",
    name: { fa: "حرم حضرت عبدالعظیم", en: "Haram-e Hazrat-e Abdol Azim" },
    location: { lat: 35.5916, lng: 51.4391 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "under_construction",
  },
  {
    id: "meydan-e-hazrat-e-abdol-azim",
    name: { fa: "میدان حضرت عبدالعظیم", en: "Meydan-e Hazrat-e Abdol Azim" },
    location: { lat: 35.5935, lng: 51.4406 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "under_construction",
  },
  {
    id: "ebn-e-babviyeh",
    name: { fa: "ابن بابویه", en: "Ebn-e Babviyeh" },
    location: { lat: 35.6037, lng: 51.4463 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "under_construction",
  },
  {
    id: "cheshmeh-ali",
    name: { fa: "چشمه علی", en: "Cheshmeh Ali" },
    location: { lat: 35.6099, lng: 51.455 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "under_construction",
  },
  {
    id: "shohada-ye-dowlat-abad",
    name: { fa: "شهدای دولت‌آباد", en: "Shohada-ye Dowlat Abad" },
    location: { lat: 35.623, lng: 51.4639 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "kiyan-shahr",
    name: { fa: "کیان شهر", en: "Kiyan Shahr" },
    location: { lat: 35.6392, lng: 51.4603 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "besat",
    name: { fa: "بعثت", en: "Be'sat" },
    location: { lat: 35.6471, lng: 51.4498 },
    amenities: { wc: true, elevator: false, atm: true, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-rezaei",
    name: { fa: "شهید رضایی", en: "Shahid Rezaei" },
    location: { lat: 35.6609, lng: 51.4514 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "meydan-e-khorasan",
    name: { fa: "میدان خراسان", en: "Meydan-e Khorasan" },
    location: { lat: 35.6728, lng: 51.4478 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shohada-ye-hefdah-e-shahrivar",
    name: { fa: "شهدای هفده شهریور", en: "Shohada-ye Hefdah-e Shahrivar" },
    location: { lat: 35.6809, lng: 51.4491 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "amirkabir",
    name: { fa: "امیرکبیر", en: "Amirkabir" },
    location: { lat: 35.6861, lng: 51.44802 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "meydan-e-shohada",
    name: { fa: "میدان شهدا", en: "Meydan-e Shohada" },
    location: { lat: 35.690381, lng: 51.447237 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "sarbaz",
    name: { fa: "سرباز", en: "Sarbaz" },
    location: { lat: 35.7077, lng: 51.4402 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "bahar-shiraz-khanevadeh-hospital",
    name: { fa: "بهار شیراز (بیمارستان خانواده)", en: "Bahar Shiraz (Khanevadeh Hospital)" },
    location: { lat: 35.7122, lng: 51.4325 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shohada-ye-haftom-e-tir",
    name: { fa: "شهدای هفتم تیر", en: "Shohada-ye Haftom-e Tir" },
    location: { lat: 35.715986, lng: 51.426042 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "maryam-e-moghaddas",
    name: { fa: "مریم مقدس (س)", en: "Maryam-e Moghaddas" },
    location: { lat: 35.7133, lng: 51.4164 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "meydan-e-hazrat-vali-asr",
    name: { fa: "میدان حضرت ولیعصر", en: "Meydan-e Hazrat Vali Asr" },
    location: { lat: 35.7115282, lng: 51.4070255 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "bustan-e-laleh",
    name: { fa: "بوستان لاله", en: "Bustan-e Laleh" },
    location: { lat: 35.7106, lng: 51.3951 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "karagar",
    name: { fa: "کارگر", en: "Karagar" },
    location: { lat: 35.7145, lng: 51.3875 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "daneshgah-e-tarbiat-modarres",
    name: { fa: "دانشگاه تربیت مدرس", en: "Daneshgah-e Tarbiat Modarres" },
    location: { lat: 35.7271, lng: 51.3844 },
    amenities: { wc: true, elevator: false, atm: true, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahrak-e-azmayesh",
    name: { fa: "شهرک آزمایش", en: "Shahrak-e Azmayesh" },
    location: { lat: 35.7305, lng: 51.366 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "marzdaran",
    name: { fa: "مرزداران", en: "Marzdaran" },
    location: { lat: 35.7348, lng: 51.3525 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "yadegar-e-imam",
    name: { fa: "یادگار امام", en: "Yadegar-e Imam" },
    location: { lat: 35.7401, lng: 51.3402 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-ashrafi-esfahani",
    name: { fa: "شهید اشرفی اصفهانی", en: "Shahid Ashrafi Esfahani" },
    location: { lat: 35.7483, lng: 51.3287 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahid-sattari",
    name: { fa: "شهید ستاری", en: "Shahid Sattari" },
    location: { lat: 35.7512, lng: 51.3162 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "ayatollah-kashani",
    name: { fa: "آیت‌الله کاشانی", en: "Ayatollah Kashani" },
    location: { lat: 35.741428, lng: 51.301673 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahr-e-ziba",
    name: { fa: "شهر زیبا", en: "Shahr-e Ziba" },
    location: { lat: 35.7437, lng: 51.2843 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shahran",
    name: { fa: "شهران", en: "Shahran" },
    location: { lat: 35.7585, lng: 51.2701 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "shohada-ye-kan",
    name: { fa: "شهدای کن", en: "Shohada-ye Kan" },
    location: { lat: 35.7693, lng: 51.2588 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "kouhsar",
    name: { fa: "کوهسار", en: "Kouhsar" },
    location: { lat: 35.78, lng: 51.245 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "varzeshgah-e-takhti",
    name: { fa: "ورزشگاه تختی", en: "Varzeshgah-e Takhti" },
    location: { lat: 35.6706, lng: 51.5088 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "basij",
    name: { fa: "بسیج", en: "Basij" },
    location: { lat: 35.667159, lng: 51.489404 },
    amenities: { wc: false, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "ahang",
    name: { fa: "آهنگ", en: "Ahang" },
    location: { lat: 35.6681, lng: 51.4769 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "chehel-tan-e-doulab",
    name: { fa: "چهل تن دولاب", en: "Chehel Tan-e Doulab" },
    location: { lat: 35.6742, lng: 51.4654 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "meydan-e-giyam",
    name: { fa: "میدان قیام", en: "Meydan-e Giyam" },
    location: { lat: 35.6717, lng: 51.4358 },
    amenities: { wc: true, elevator: false, atm: true, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "mowlavi",
    name: { fa: "مولوی", en: "Mowlavi" },
    location: { lat: 35.6683, lng: 51.4248 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "helal-ahmar",
    name: { fa: "هلال احمر", en: "Helal Ahmar" },
    location: { lat: 35.6666, lng: 51.3969 },
    amenities: { wc: true, elevator: false, atm: true, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "beryanak",
    name: { fa: "بریانک", en: "Beryanak" },
    location: { lat: 35.6755, lng: 51.3868 },
    amenities: { wc: true, elevator: true, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "komeyl",
    name: { fa: "کمیل", en: "Komeyl" },
    location: { lat: 35.682491, lng: 51.380143 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: true, police: true },
    status: "operational",
  },
  {
    id: "roudaki",
    name: { fa: "رودکی", en: "Roudaki" },
    location: { lat: 35.6897, lng: 51.3788 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "modafean-e-salamat",
    name: { fa: "مدافعان سلامت", en: "Modafean-e Salamat" },
    location: { lat: 35.7134, lng: 51.3811 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "boostan-e-goftegou",
    name: { fa: "بوستان گفتگو", en: "Boostan-e Goftegou" },
    location: { lat: 35.7388, lng: 51.3755 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "milad-tower",
    name: { fa: "برج میلاد", en: "Milad Tower" },
    location: { lat: 35.7446, lng: 51.375 },
    amenities: { wc: true, elevator: true, atm: true, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "meydan-e-sanat",
    name: { fa: "میدان صنعت", en: "Meydan-e San'at" },
    location: { lat: 35.754386, lng: 51.367808 },
    amenities: { wc: false, elevator: false, atm: false, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: true, parking: true, police: true },
    status: "operational",
  },
  {
    id: "shahid-dadman",
    name: { fa: "شهید دادمان", en: "Shahid Dadman" },
    location: { lat: 35.7653, lng: 51.36 },
    amenities: { wc: true, elevator: false, atm: false, coffeeShop: false, fastFood: false, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
  {
    id: "meydan-e-ketab",
    name: { fa: "میدان کتاب", en: "Meydan-e Ketab" },
    location: { lat: 35.7777, lng: 51.3493 },
    amenities: { wc: true, elevator: false, atm: true, coffeeShop: false, fastFood: true, groceryStore: false, freeWifi: false, prayerRoom: false, parking: false, police: true },
    status: "operational",
  },
];
