// Version pointer for hot-updatable metro datasets (timetable + stations).
//
// Mirrors the holidays update architecture: a tiny same-origin manifest is
// polled with `cache: "no-store"` at startup; only new/changed
// content-addressed chunks are downloaded. The manifest itself must NEVER
// be precached (see serwist.config.js globIgnores + the NetworkFirst SW
// rule) — otherwise clients would poll a frozen copy and never discover
// updates.
//
// Schema v2 (generated by scripts/generate-metro-data.mjs):
// {
//   "schemaVersion": 2, "dataVersion": "<content hash short>",
//   "schedule": { "version", "sha256", "size",
//     "chunks": { "<scheduleKey>": { "url", "sha256", "size" } } },
//   "stations": { "version", "url", "sha256", "size" }
// }
// Schema v1 (legacy monolith, accepted during transition):
// { "schemaVersion": 1, "schedule": { "version", "url" } }

export const METRO_DATA_MANIFEST_URL = "/metro-data-manifest.json";
export const METRO_DATA_MANIFEST_SCHEMA_VERSION = 2;
const LEGACY_SCHEMA_VERSION = 1;

export interface ManifestChunk {
  url: string;
  sha256: string;
  size: number;
}

export interface MetroDataManifestSchedule {
  version: string;
  /** Legacy v1 monolith download URL (absent in v2 chunked manifests). */
  url?: string;
  sha256?: string;
  size?: number;
  /** Independently versioned timetable chunks (v2 only). */
  chunks?: Record<string, ManifestChunk>;
}

export interface MetroDataManifestStations {
  version: string;
  url: string;
  sha256: string;
  size: number;
}

export interface MetroDataManifest {
  schemaVersion: number;
  dataVersion?: string;
  schedule: MetroDataManifestSchedule;
  stations?: MetroDataManifestStations;
}

function isSameOriginPath(url: unknown): url is string {
  return typeof url === "string" && url.startsWith("/");
}

function isHexHash(v: unknown): v is string {
  return typeof v === "string" && /^[0-9a-fA-F]{12,128}$/.test(v);
}

function parseChunk(raw: unknown): ManifestChunk | null {
  if (typeof raw !== "object" || raw === null) return null;
  const c = raw as Record<string, unknown>;
  if (!isSameOriginPath(c.url)) return null;
  if (!isHexHash(c.sha256)) return null;
  if (typeof c.size !== "number" || !Number.isInteger(c.size) || c.size <= 0) {
    return null;
  }
  return { url: c.url, sha256: (c.sha256 as string).toLowerCase(), size: c.size };
}

function parseStations(raw: unknown): MetroDataManifestStations | null {
  if (typeof raw !== "object" || raw === null) return null;
  const s = raw as Record<string, unknown>;
  if (typeof s.version !== "string" || s.version.length === 0) return null;
  const chunk = parseChunk(s);
  if (!chunk) return null;
  return { version: s.version, ...chunk };
}

/**
 * Validate + normalize a downloaded manifest. Returns null when unusable.
 * Accepts schema v1 (legacy monolith) and v2 (chunked). Unknown extra
 * fields are ignored so future datasets can extend this file without
 * breaking older clients. Same-origin URLs only — the updater must never
 * fetch upstream/third-party.
 */
export function parseMetroDataManifest(raw: unknown): MetroDataManifest | null {
  if (typeof raw !== "object" || raw === null) return null;
  const d = raw as Record<string, unknown>;
  if (d.schemaVersion !== METRO_DATA_MANIFEST_SCHEMA_VERSION && d.schemaVersion !== LEGACY_SCHEMA_VERSION) {
    return null;
  }
  if (typeof d.schedule !== "object" || d.schedule === null) return null;
  const s = d.schedule as Record<string, unknown>;
  if (typeof s.version !== "string" || s.version.length === 0) return null;
  const schedule: MetroDataManifestSchedule = { version: s.version };

  if (d.schemaVersion === LEGACY_SCHEMA_VERSION) {
    if (!isSameOriginPath(s.url)) return null;
    schedule.url = s.url;
    return { schemaVersion: LEGACY_SCHEMA_VERSION, schedule };
  }

  // v2: chunks required, non-empty, unique ids (object keys are unique by
  // construction — an empty map or malformed entry still fails closed).
  if (typeof s.chunks !== "object" || s.chunks === null) return null;
  const chunkEntries = Object.entries(s.chunks);
  if (chunkEntries.length === 0) return null;
  const chunks: Record<string, ManifestChunk> = {};
  for (const [key, value] of chunkEntries) {
    if (key.length === 0) return null;
    const parsed = parseChunk(value);
    if (!parsed) return null;
    chunks[key] = parsed;
  }
  schedule.chunks = chunks;
  if (isHexHash(s.sha256)) schedule.sha256 = (s.sha256 as string).toLowerCase();
  if (typeof s.size === "number" && Number.isInteger(s.size) && s.size > 0) {
    schedule.size = s.size;
  }

  const out: MetroDataManifest = {
    schemaVersion: METRO_DATA_MANIFEST_SCHEMA_VERSION,
    schedule,
  };
  if (typeof d.dataVersion === "string" && d.dataVersion.length > 0) {
    out.dataVersion = d.dataVersion;
  }
  if (d.stations !== undefined) {
    const stations = parseStations(d.stations);
    if (!stations) return null;
    out.stations = stations;
  }
  return out;
}

/**
 * True when the remote dataset is worth downloading. Empty current version
 * means "bundled/unknown vintage" (pre-bundled-meta clients): any
 * well-formed remote version counts as newer. Content-hash versions (v2)
 * compare by inequality; dotted numeric versions keep legacy ordering.
 */
export function isNewerScheduleVersion(remote: string, current: string): boolean {
  if (remote === current) return false;
  if (current.length === 0) return true;
  const hashLike = (v: string) => /^[0-9a-fA-F]{12,128}$/.test(v);
  if (hashLike(remote) || hashLike(current)) return remote.toLowerCase() !== current.toLowerCase();
  const pa = remote.split(".").map((s) => Number(s));
  const pb = current.split(".").map((s) => Number(s));
  const numeric =
    pa.length === pb.length &&
    pa.every((n) => Number.isInteger(n)) &&
    pb.every((n) => Number.isInteger(n));
  if (numeric) {
    for (let i = 0; i < pa.length; i++) {
      if (pa[i] !== pb[i]) return pa[i] > pb[i];
    }
    return false;
  }
  return remote > current;
}
