// Pure service-worker route predicates for the dynamic timetable.
//
// Extracted (not inlined in app/sw.ts) so unit tests can prove the routing
// contract without running a worker:
// - the manifest is never served from precache (NetworkFirst at runtime);
// - a version-pinned schedule download NEVER resolves to the precached
//   bare `/schedule-data.json` entry (NetworkOnly when a query is present).
// app/sw.ts imports these — behavior and tests cannot drift apart.

/** True for the tiny update pointer (must revalidate, never freeze). */
export function isDataManifestRequest(pathname: string): boolean {
  return pathname === "/metro-data-manifest.json";
}

/**
 * True for a version-pinned timetable download, e.g.
 * `/schedule-data.json?v=2026-09-13.1`. The bare precached fallback
 * (`/schedule-data.json` with NO query) intentionally returns false here —
 * it keeps serving deterministically from the precache.
 */
export function isVersionedScheduleRequest(pathname: string, search: string): boolean {
  return pathname === "/schedule-data.json" && search.length > 0;
}

/**
 * True for an immutable content-addressed metro-data chunk, e.g.
 * `/data/schedule-1.0d3199649e75.json` or `/data/stations.587df666a707.json`.
 * Generated by scripts/generate-metro-data.mjs; the 12-hex content hash in
 * the filename guarantees a different URL whenever content changes, so
 * long-lived immutable caching is safe. Never matches the bare precached
 * `/schedule-data.json` bootstrap or the manifest pointer.
 */
export function isScheduleChunkRequest(pathname: string): boolean {
  if (!pathname.startsWith("/data/")) return false;
  return (
    /^\/data\/schedule-.+\.[0-9a-f]{12}\.json$/.test(pathname) ||
    /^\/data\/stations\.[0-9a-f]{12}\.json$/.test(pathname)
  );
}
