export type WelcomeLang = "fa" | "en";
export type WelcomeNavKey = "route" | "stations" | "nearby" | "map";

export const WELCOME_NAV: { key: WelcomeNavKey; href: string }[] = [
  { key: "route", href: "/route" },
  { key: "stations", href: "/stations" },
  { key: "nearby", href: "/nearby" },
  { key: "map", href: "/map" },
];

const fa = {
  hero: {
    eyebrow: "مسیریاب مترو",
    city: "تهران",
    h1a: "مسیریاب مترو،",
    h1b: "ساده و سریع",
    sub: "مبدأ و مقصد را بزن — بهترین مسیر، زمان رسیدن و قطار بعدی را ببین.",
    ctaPrimary: "شروع مسیریابی",
    ctaSecondary: "دیدن نقشه",
    trust: ["رایگان، برای همیشه", "بدون ثبت‌نام و بدون تبلیغ", "آفلاین کار می‌کند"],
    panel: {
      live: "زنده",
      lineLabel: "خط",
      depart: "حرکت",
      arrive: "رسیدن",
      duration: "زمان سفر",
      stops: "ایستگاه",
      changes: "تعویض خط",
      walk: "پیاده‌روی",
      minutes: "دقیقه",
      transferAt: "تعویض در",
      nextTrain: "قطار بعدی",
      following: "حرکت‌های بعدی",
      note: "بر اساس زمان‌بندی امروز",
      localTime: "ساعت تهران",
      waiting: "در حال گرفتن زمان…",
    },
  },
  demo: {
    eyebrow: "دمو",
    title: "همین‌جا امتحانش کن",
    desc: "دو ایستگاه را انتخاب کن تا لینک مسیر آماده شود.",
    fromLabel: "مبدأ",
    toLabel: "مقصد",
    fromPlaceholder: "مثلاً تجریش",
    toPlaceholder: "مثلاً صادقیه",
    swap: "جابه‌جایی مبدأ و مقصد",
    cta: "امتحان در اپ",
    estimate: "تخمین حدودی",
    noMatch: "ایستگاهی با این نام پیدا نشد",
    hint: "این لینک قابل اشتراک است و همان مسیر را در اپ باز می‌کند.",
    copy: "کپی لینک",
    copied: "کپی شد",
    minutes: "دقیقه",
    stops: "ایستگاه",
    changes: "تعویض خط",
    sameStation: "مبدأ و مقصد یکی است",
  },
  features: {
    eyebrow: "چرا متو را ساختیم",
    title: "در مترو گم شده‌ای؟ ما هم شده بودیم.",
    desc: "متو را ساختیم چون خودمان هر روز سرِ همان سؤال‌ها می‌ماندیم: از کجا سوار شوم، کجا خط عوض کنم، قطار بعدی کی است. حالا همه‌اش این‌جاست.",
    items: [
      {
        tag: "۰۱",
        title: "مسیریابی هوشمند",
        desc: "اسم جای معروف را بنویس؛ «ایران‌مال» به نزدیک‌ترین ایستگاه می‌رسد. مبدأ و مقصد را جابه‌جا کن و لینک مسیر را بفرست.",
        chips: ["جست‌وجوی مکان", "لینک قابل اشتراک"],
      },
      {
        tag: "۰۲",
        title: "زمان رسیدن واقعی",
        desc: "محاسبه با زمان‌بندی واقعی قطارها، پیاده‌روی تعویض خط، قطار تندرو خط ۵ و سرویس پنجشنبه، جمعه و تعطیلات.",
        chips: ["قطار بعدی", "سرویس تعطیلات"],
      },
      {
        tag: "۰۳",
        title: "۱۵۱ ایستگاه، ۷ خط",
        desc: "فهرست کامل ایستگاه‌ها با فیلتر، زمان حرکت‌ها و برنامه تمام روز هر ایستگاه.",
        chips: ["۱۵۱ ایستگاه", "۷ خط"],
      },
      {
        tag: "۰۴",
        title: "نقشه واقعی",
        desc: "نقشه ساده و نمای ماهواره‌ای، با امکان روشن و خاموش کردن هر خط.",
        chips: ["نمای ماهواره", "فیلتر خط‌ها"],
      },
      {
        tag: "۰۵",
        title: "نزدیک من",
        desc: "با موقعیت مکانی نزدیک‌ترین ایستگاه‌ها را ببین، همراه با امکانات ایستگاه و لینک مسیریابی.",
        chips: ["سرویس بهداشتی", "آسانسور", "عابربانک", "وای‌فای"],
      },
      {
        tag: "۰۶",
        title: "آفلاین و فارسی",
        desc: "روی گوشی نصب می‌شود، بدون اینترنت باز می‌شود، کاملاً راست‌به‌چپ و با تاریخ شمسی.",
        chips: ["نصب روی گوشی", "تاریخ شمسی"],
      },
    ],
  },
  steps: {
    eyebrow: "چطور کار می‌کند",
    title: "سه قدم، تمام",
    items: [
      {
        title: "مبدأ و مقصد را انتخاب کن",
        desc: "اسم ایستگاه یا یک جای معروف را بنویس؛ پیشنهادها همان‌جا ظاهر می‌شوند.",
      },
      {
        title: "مسیر و زمان را ببین",
        desc: "بهترین مسیر با تعداد ایستگاه‌ها، تعویض خط، زمان رسیدن و قطار بعدی.",
      },
      {
        title: "لینک را به اشتراک بگذار",
        desc: "لینک را برای همراهت بفرست؛ همان صفحه مسیر بدون نصب چیزی باز می‌شود.",
      },
    ],
    cta: "شروع مسیریابی",
  },
  pwa: {
    eyebrow: "زیر زمین هم کار می‌کند",
    title: "اینترنت نباشد، متو هست.",
    desc: "همان‌جا که بیشتر از همه لازمش داری — چند طبقه زیر زمین، بین دو ایستگاه — اینترنت قطع است. متو برای همان لحظه ساخته شده.",
    storyTitle: "چطور بدون اینترنت کار می‌کند؟",
    story: [
      { title: "یک بار باز کن", desc: "روی وای‌فای یا دیتا، فقط یک بار متو را باز کن." },
      { title: "خودش ذخیره می‌شود", desc: "نقشه، ۱۵۱ ایستگاه و زمان‌بندی‌ها روی گوشی‌ات می‌مانند." },
      { title: "زیر زمین باز می‌شود", desc: "دفعه بعد، حتی بدون یک خط آنتن، همه چیز آماده است." },
    ],
    storyNote: "فقط زمان لحظه‌ای قطار بعدی به اینترنت نیاز دارد؛ مسیر و نقشه همیشه هستند.",
    install: "نصب وب‌اپ (PWA)",
    installPwaNote: "بدون دانلود، از خود مرورگر — فقط یک آیکون اضافه می‌شود",
    installedPwa: "داری از نسخه نصب‌شده وب استفاده می‌کنی",
    installedPwaHint: "این صفحه داخل نسخه نصب‌شده وب (PWA) باز است — نیازی به کار دیگری نیست",
    installedTwa: "داری از اپ اندروید استفاده می‌کنی",
    installedTwaHint: "این صفحه داخل اپ اندروید نصب‌شده (APK) باز است — نیازی به کار دیگری نیست",
    twaOnDevice: "اپ اندروید روی این گوشی نصب است",
    twaOnDeviceHint:
      "اپ اندروید (ir.metto.app) روی این دستگاه نصب است؛ الان داری نسخه مرورگر را می‌بینی. برای باز کردنش آیکون متو را در لیست برنامه‌ها بزن.",
    detectionNote:
      "مرورگر همیشه نمی‌تواند بفهمد چیزی نصب است یا نه: وقتی داخل نسخه نصب‌شده وب یا اپ اندروید باشی می‌فهمیم، و نصب بودن اپ اندروید را هم در کروم اندروید می‌پرسیم. اگر نصب کرده‌ای ولی اینجا نشان نمی‌دهد، آیکون متو را در صفحه اصلی یا لیست برنامه‌ها ببین.",
    sameApp:
      "وب‌اپ یا APK — خود برنامه یکی است و هر دو آفلاین‌اند: وب‌اپ بدون دانلود، از مرورگر · APK حدود ۱٫۳ مگ",
    noInstallTitle: "نصب اختیاری است؛ آفلاین بودن نه",
    noInstallDesc:
      "متو یک سایت است و همان‌طور که هست، آفلاین کار می‌کند. نصب کردن فقط یک آیکون به صفحه اصلی گوشی‌ات اضافه می‌کند تا سریع‌تر بازش کنی.",
    storesTitle: "اپ اندروید (APK) — همان برنامه",
    storesSubtitle: "اندروید می‌خواهی؟ یکی را انتخاب کن؛ وب‌اپ بالا بدون دانلود است",
    twa: "دانلود مستقیم (APK)",
    twaNote: "ساخت خودکار با گیت‌هاب · حدود ۱٫۳ مگ",
    myket: "مایکت",
    myketNote: "اندروید",
    bazar: "کافه بازار",
    bazarNote: "به‌زودی",
    play: "گوگل پلی",
    playNote: "به‌زودی",
    hintTitle: "چطور نصبش کنم؟",
    steps: [
      "کروم: منو ← «افزودن به صفحه اصلی».",
      "سافاری: دکمه اشتراک‌گذاری ← «افزودن به صفحه اصلی».",
      "بار اول که آنلاین است، داده ایستگاه‌ها ذخیره می‌شود.",
    ],
    note: "اگر دکمه نصب را نمی‌بینی، از منوی مرورگرت استفاده کن.",
  },
  faq: {
    eyebrow: "پرسش‌های رایج",
    title: "سؤال‌های پرتکرار",
    items: [
      {
        q: "آیا رایگان است؟",
        a: "بله، کامل رایگان است — بدون تبلیغ، برای همیشه. نه ثبت‌نام می‌خواهد، نه پرداخت. سرور و داده‌ها فقط با حمایت داوطلبانه کاربرها پیش می‌رود؛ اگر دوست داشتی، از بخش «حمایت از متو» در پایین همین صفحه می‌توانی کمک کنی.",
      },
      {
        q: "کدام شهرها؟",
        a: "فعلاً مترو تهران با ۱۵۱ ایستگاه و ۷ خط. شهرهای دیگر به‌مرور اضافه می‌شوند؛ برنامه از اول برای چند شهر ساخته شده است.",
      },
      {
        q: "آیا آفلاین کار می‌کند؟",
        a: "بله. بعد از اولین اجرا، پوسته برنامه و داده ایستگاه‌ها روی گوشی می‌ماند و زیر زمین هم باز می‌شود. فقط زمان لحظه‌ای حرکت قطارها به اینترنت نیاز دارد.",
      },
      {
        q: "داده‌ها از کجاست؟",
        a: "ایستگاه‌ها و خط‌ها از مجموعه‌داده باز mostafa-kheibary گرفته شده و زمان‌بندی‌ها بر اساس اطلاعات اعلام‌شده شرکت مترو است. اگر جایی اشتباه دیدی، روی گیت‌هاب بگو تا درستش کنیم.",
      },
    ],
    more: "چیز دیگری می‌خواهی بدانی؟",
    ask: "پرسش را روی گیت‌هاب بنویس",
  },
  donate: {
    eyebrow: "حمایت از متو",
    title: "رایگان. بدون تبلیغ. برای همیشه.",
    desc: "متو هیچ پولی نمی‌گیرد و هیچ تبلیغی نشان نمی‌دهد — هزینه زیرساخت و زمان توسعه‌اش فقط با حمایت داوطلبانه کسانی که ازش استفاده می‌کنند پیش می‌رود.",
    paysTitle: "حمایتت صرف چه می‌شود؟",
    pays: ["سرور را روشن نگه می‌دارد", "داده‌ها و زمان‌بندی را به‌روز نگه می‌دارد", "قابلیت‌ها و شهرهای جدید را می‌سازد"],
    primary: "حمایت مالی",
    primaryNote: "از طریق ریمیت",
    secondary: "ستاره روی گیت‌هاب",
    altTitle: "حمایت گران‌بها لزوماً پولی نیست:",
    altWays: ["متو را به یک دوست معرفی کن", "خطای داده را گزارش بده", "ایده‌ات را برایمان بنویس"],
    slotLabel: "جای تبلیغ",
    adBadge: "تبلیغ",
    neverCaption: "این‌جا هیچ‌وقت چیزی مثل این نمی‌بینی.",
    thanks: "پیشاپیش از کمکت ممنون",
  },
  footer: {
    tagline: "نقشه و مسیریابی مترو، بدون حساب و کتاب.",
    madeBy: "ساخته‌شده توسط",
    dataSource: "داده‌های مترو از",
    linksTitle: "صفحه‌ها",
    github: "گیت‌هاب",
    cityNote: "فعلاً تهران · شهرهای بعدی در راه‌اند",
    rights: "داده‌ها آزاد است؛ با ذکر منبع استفاده کنید.",
  },
  misc: {
    skip: "رفتن به محتوا",
    scroll: "اسکرول کن",
  },
};

const en: typeof fa = {
  hero: {
    eyebrow: "Metro route planner",
    city: "Tehran",
    h1a: "Metro routing,",
    h1b: "simple and fast",
    sub: "Type an origin and a destination — see the best route, the arrival time and the next train.",
    ctaPrimary: "Start planning",
    ctaSecondary: "View map",
    trust: ["Free, forever", "No sign-up, no ads", "No install needed", "Offline"],
    panel: {
      live: "Live",
      lineLabel: "Line",
      depart: "Depart",
      arrive: "Arrive",
      duration: "Trip time",
      stops: "stops",
      changes: "changes",
      walk: "walking",
      minutes: "min",
      transferAt: "Change at",
      nextTrain: "Next train",
      following: "Following departures",
      note: "Based on today's timetable",
      localTime: "Tehran time",
      waiting: "Fetching times…",
    },
  },
  demo: {
    eyebrow: "Demo",
    title: "Try it right here",
    desc: "Pick two stations and the link is ready to go.",
    fromLabel: "From",
    toLabel: "To",
    fromPlaceholder: "e.g. Tajrish",
    toPlaceholder: "e.g. Sadeghiyeh",
    swap: "Swap origin and destination",
    cta: "Try in the app",
    estimate: "rough estimate",
    noMatch: "No station with that name",
    hint: "The link is shareable and opens the same trip inside the app.",
    copy: "Copy link",
    copied: "Copied",
    minutes: "min",
    stops: "stops",
    changes: "changes",
    sameStation: "Origin and destination are the same",
  },
  features: {
    eyebrow: "Why we built metto",
    title: "Lost in the metro? So were we.",
    desc: "We built metto because we kept asking the same questions every day: where do I get on, where do I change lines, when is the next train. Now it is all here.",
    items: [
      {
        tag: "01",
        title: "Smart routing",
        desc: "Search a place like “Iran Mall” and it snaps to the nearest station. Swap the ends and share the link.",
        chips: ["Place search", "Shareable link"],
      },
      {
        tag: "02",
        title: "Real arrival times",
        desc: "Timetable-aware ETA with transfer walking time, the Line 5 express and Thursday / Friday / holiday service.",
        chips: ["Next train", "Holiday service"],
      },
      {
        tag: "03",
        title: "151 stations, 7 lines",
        desc: "The full station list with filters, departures and a full-day timesheet for every station.",
        chips: ["151 stations", "7 lines"],
      },
      {
        tag: "04",
        title: "A real map",
        desc: "A clean minimalist map and a satellite view, with a toggle for every single line.",
        chips: ["Satellite view", "Line toggles"],
      },
      {
        tag: "05",
        title: "Near me",
        desc: "GPS finds the closest stations, with restroom, elevator, ATM and Wi-Fi info plus a directions link.",
        chips: ["Restroom", "Elevator", "ATM", "Wi-Fi"],
      },
      {
        tag: "06",
        title: "Offline & Persian-first",
        desc: "An installable PWA with an offline shell, a full RTL layout and Jalali dates.",
        chips: ["Installable", "Jalali dates"],
      },
    ],
  },
  steps: {
    eyebrow: "How it works",
    title: "Three steps, that's it",
    items: [
      {
        title: "Pick an origin and a destination",
        desc: "Type a station or a well-known place — suggestions show up as you type.",
      },
      {
        title: "See the route and the time",
        desc: "The best route with stop count, line changes, arrival time and the next train.",
      },
      {
        title: "Share the link",
        desc: "Send the link to whoever is travelling with you; it opens the same trip with nothing to install.",
      },
    ],
    cta: "Start planning",
  },
  pwa: {
    eyebrow: "Works underground",
    title: "No internet? Still metto.",
    desc: "Right where you need it most — a few floors down, between two stations — the connection is gone. metto is built for exactly that moment.",
    storyTitle: "How does it work with no internet?",
    story: [
      { title: "Open it once", desc: "On Wi-Fi or data, just open metto one time." },
      { title: "It saves itself", desc: "The map, all 151 stations and the timetables stay on your phone." },
      { title: "It opens underground", desc: "Next time, even with zero bars, everything is ready." },
    ],
    storyNote: "Only the live next-train time needs a connection; routes and the map are always there.",
    install: "Install web app (PWA)",
    installPwaNote: "No download, straight from the browser — just adds an icon",
    installedPwa: "You're using the installed web app",
    installedPwaHint: "This page is running inside the installed web app (PWA) — nothing left to do",
    installedTwa: "You're using the Android app",
    installedTwaHint: "This page is running inside the installed Android app (APK) — nothing left to do",
    twaOnDevice: "Android app is installed on this phone",
    twaOnDeviceHint:
      "The Android app (ir.metto.app) is installed on this device; you're looking at the browser version right now. Open it from the metto icon in your app list.",
    detectionNote:
      "Browsers can't always tell what's installed: we detect it when you're running inside the installed web app or the Android app, and on Android Chrome we can also ask whether the Android app is installed. If you installed it but don't see it here, look for the metto icon on your home screen or app list.",
    sameApp:
      "PWA or APK — same app, both offline: web app needs no download, from the browser · APK is ~1.3 MB",
    noInstallTitle: "Installing is optional. Offline isn't.",
    noInstallDesc:
      "metto is a website and it works offline exactly as it is. Installing only adds an icon to your home screen so you can open it faster.",
    storesTitle: "Android app (APK) — the same app",
    storesSubtitle: "Want Android? Pick one; the web app above needs no download",
    twa: "Direct APK download",
    twaNote: "Auto-built on GitHub · about 1.3 MB",
    myket: "Myket",
    myketNote: "Android",
    bazar: "Cafe Bazaar",
    bazarNote: "Coming soon",
    play: "Google Play",
    playNote: "Coming soon",
    hintTitle: "How do I install it?",
    steps: [
      "Chrome: menu → “Add to Home screen”.",
      "Safari: share button → “Add to Home Screen”.",
      "The first time you are online, station data is saved on the device.",
    ],
    note: "If you don't see the install button, use your browser menu instead.",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Questions people ask",
    items: [
      {
        q: "Is it free?",
        a: "Completely — with no ads, forever. No sign-up, no payment. Hosting and data run purely on voluntary user support; if you feel like it, the “Support metto” section at the bottom of the page links to Reymit.",
      },
      {
        q: "Which cities?",
        a: "Right now the Tehran metro with 151 stations and 7 lines. More cities are being added — the app was built for multiple cities from day one.",
      },
      {
        q: "Does it work offline?",
        a: "Yes. After the first run the app shell and the station data stay on your phone, so it opens underground too. Only live departure times need a connection.",
      },
      {
        q: "Where does the data come from?",
        a: "Stations and lines come from the open dataset by mostafa-kheibary, and timetables follow the metro company's published information. Spotted a mistake? Say so on GitHub and we will fix it.",
      },
    ],
    more: "Anything else you want to know?",
    ask: "Ask on GitHub",
  },
  donate: {
    eyebrow: "Support metto",
    title: "Free. No ads. Forever.",
    desc: "metto charges nothing and never shows advertising — its hosting and development time run purely on voluntary support from the people who use it.",
    paysTitle: "What your support pays for",
    pays: ["Keeps the server running", "Keeps data and timetables current", "Builds new features and cities"],
    primary: "Donate",
    primaryNote: "via Reymit",
    secondary: "Star on GitHub",
    altTitle: "Not all valuable support is money:",
    altWays: ["Tell a friend about metto", "Report a data mistake", "Share an idea with us"],
    slotLabel: "Ad slot",
    adBadge: "Ad",
    neverCaption: "You will never see something like this here.",
    thanks: "Thank you in advance",
  },
  footer: {
    tagline: "Metro map and routing, without the fuss.",
    madeBy: "Built by",
    dataSource: "Metro data from",
    linksTitle: "Pages",
    github: "GitHub",
    cityNote: "Tehran for now · more cities coming",
    rights: "The data is free to use with attribution.",
  },
  misc: {
    skip: "Skip to content",
    scroll: "Scroll",
  },
};

export type WelcomeContent = typeof fa;
export const WELCOME_CONTENT: Record<WelcomeLang, WelcomeContent> = { fa, en };
