#!/usr/bin/env node
/**
 * Generate lib/metro/stations.ts from canonical upstream JSON + Metto overrides.
 *
 * Usage:
 *   node scripts/generate-stations.ts --source data/tehran-metro-stations.json
 *   pnpm generate:stations --source data/tehran-metro-stations.json
 *
 * Rules (locked):
 * - Canonical coordinates + amenities always come from the upstream JSON.
 * - 149 canonical stations copy upstream latitude/longitude exactly.
 * - Shahid Sepahbod Qasem Soleimani uses the explicit Metto override in
 *   scripts/metto-overrides.json (coordinates only; amenities stay canonical).
 * - Shahid Fakhrizadeh (Metto-specific, not upstream) is inserted from
 *   overrides and excluded from canonical validation.
 * - Amenities: true->true, false->false, null/missing->null. NEVER ?? false.
 *   `fastFoodn` (upstream typo) is ignored; missing `fastFood` becomes null.
 * - IDs are stable kebab-case slugs of the English name; fa/en names come
 *   from upstream (fa from translations.fa). Statuses come from overrides
 *   (default operational). No topology/route/segment changes here.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");

type UpstreamStation = {
  name: string;
  translations?: { fa?: string };
  latitude: number;
  longitude: number;
  wc?: boolean | null;
  elevator?: boolean | null;
  atm?: boolean | null;
  coffeeShop?: boolean | null;
  fastFood?: boolean | null;
  groceryStore?: boolean | null;
  freeWifi?: boolean | null;
  prayerRoom?: boolean | null;
  bicycleParking?: boolean | null;
  metroPolice?: boolean | null;
  [k: string]: unknown;
};

type Overrides = {
  soleimaniOverride: { en: string; location: { lat: number; lng: number } };
  statusOverrides: Record<string, string>;
  fakhrizadeh: {
    id: string;
    name: { fa: string; en: string };
    location: { lat: number; lng: number };
    amenities: Record<string, boolean | null>;
    amenitiesVerified: boolean;
    status: string;
    insertAfterEn: string;
  };
};

function parseSourceArg(argv: string[]): string | undefined {
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--source" && i + 1 < argv.length) return argv[i + 1];
    const m = argv[i].match(/^--source=(.+)$/);
    if (m) return m[1];
  }
  return undefined;
}

export function slugifyEnglishName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[’‘'‛`]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function toNullable(v: unknown): boolean | null {
  if (v === undefined || v === null) return null;
  // Upstream canonical values are strictly true/false; preserve exactly.
  return v as boolean;
}

function fmtAmenityValue(v: boolean | null): string {
  if (v === null) return "null";
  return v ? "true" : "false";
}

function main(): void {
  const sourceArg = parseSourceArg(process.argv.slice(2)) ?? "data/tehran-metro-stations.json";
  const sourcePath = resolve(repoRoot, sourceArg);
  const overridesPath = join(here, "metto-overrides.json");
  const outPath = join(repoRoot, "lib", "metro", "stations.ts");

  let upstreamRaw: string;
  try {
    upstreamRaw = readFileSync(sourcePath, "utf8");
  } catch {
    console.error(
      `generate-stations: source file not found: ${sourcePath} (from --source ${sourceArg}). Refusing to fall back to another dataset.`,
    );
    process.exit(1);
  }
  const upstream = JSON.parse(upstreamRaw) as Record<string, UpstreamStation>;
  const upstreamNames = Object.keys(upstream);
  if (upstreamNames.length !== 150) {
    console.error(
      `generate-stations: expected 150 canonical stations in ${sourcePath}, found ${upstreamNames.length}. Aborting.`,
    );
    process.exit(1);
  }

  const overrides = JSON.parse(
    readFileSync(overridesPath, "utf8"),
  ) as Overrides;
  const soleimaniEn = overrides.soleimaniOverride.en;
  const soleimaniLoc = overrides.soleimaniOverride.location;

  const lines: string[] = [];
  lines.push(
    `// Auto-generated by scripts/generate-stations.ts from ${sourceArg} (upstream: tehran-metro-data, mostafa-kheibary).`,
  );
  lines.push(`// Do not edit by hand. Stable kebab-case IDs; display names preserved verbatim.`);
  lines.push(`// Coordinates: 149 canonical stations copy upstream latitude/longitude exactly;`);
  lines.push(`// Shahid Sepahbod Qasem Soleimani uses the explicit Metto override in scripts/metto-overrides.json.`);
  lines.push(`// Amenities: upstream true->true, false->false, null/missing->null (never false-defaulted).`);
  lines.push(`// Status: explicit Metto overrides in scripts/metto-overrides.json (default operational).`);
  lines.push(`// Shahid Fakhrizadeh is Metto-specific (not upstream), inserted after Golshahr.`);
  lines.push(`import type { MetroStation } from "./types";`);
  lines.push(``);
  lines.push(`export const STATIONS: MetroStation[] = [`);

  const amenityOrder = [
    "wc",
    "elevator",
    "atm",
    "coffeeShop",
    "fastFood",
    "groceryStore",
    "freeWifi",
    "prayerRoom",
    "parking",
    "police",
  ] as const;

  const f = overrides.fakhrizadeh;
  const fakhrizadehBlock = [
    `  {`,
    `    id: ${JSON.stringify(f.id)},`,
    `    name: { fa: ${JSON.stringify(f.name.fa)}, en: ${JSON.stringify(f.name.en)} },`,
    `    location: { lat: ${JSON.stringify(f.location.lat)}, lng: ${JSON.stringify(f.location.lng)} },`,
    `    amenities: { ${amenityOrder.map((k) => `${k}: ${fmtAmenityValue(f.amenities[k] as boolean | null)}`).join(", ")} },`,
    `    amenitiesVerified: false,`,
    `    status: ${JSON.stringify(f.status)},`,
    `  },`,
  ];

  for (const en of upstreamNames) {
    const u = upstream[en];
    const id = slugifyEnglishName(u.name ?? en);
    const fa = u.translations?.fa ?? "";
    const isSoleimani = (u.name ?? en) === soleimaniEn;
    const lat = isSoleimani ? soleimaniLoc.lat : u.latitude;
    const lng = isSoleimani ? soleimaniLoc.lng : u.longitude;
    const amenities: Record<string, boolean | null> = {
      wc: toNullable(u.wc),
      elevator: toNullable(u.elevator),
      atm: toNullable(u.atm),
      coffeeShop: toNullable(u.coffeeShop),
      // NOTE: upstream typo `fastFoodn` is deliberately ignored.
      fastFood: toNullable(u.fastFood),
      groceryStore: toNullable(u.groceryStore),
      freeWifi: toNullable(u.freeWifi),
      prayerRoom: toNullable(u.prayerRoom),
      parking: toNullable(u.bicycleParking),
      police: toNullable(u.metroPolice),
    };
    const status = overrides.statusOverrides[id] ?? "operational";
    lines.push(`  {`);
    lines.push(`    id: ${JSON.stringify(id)},`);
    lines.push(
      `    name: { fa: ${JSON.stringify(fa)}, en: ${JSON.stringify(u.name ?? en)} },`,
    );
    lines.push(
      `    location: { lat: ${JSON.stringify(lat)}, lng: ${JSON.stringify(lng)} },`,
    );
    lines.push(
      `    amenities: { ${amenityOrder.map((k) => `${k}: ${fmtAmenityValue(amenities[k])}`).join(", ")} },`,
    );
    lines.push(`    status: ${JSON.stringify(status)},`);
    lines.push(`  },`);
    if ((u.name ?? en) === f.insertAfterEn) {
      lines.push(...fakhrizadehBlock);
    }
  }

  lines.push(`];`);
  lines.push(``);
  writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log(
    `generate-stations: wrote ${upstreamNames.length + 1} stations to lib/metro/stations.ts from ${sourceArg}`,
  );
}

main();
